In [7]:
import pandas as pd
from ast import literal_eval

In [2]:
df=pd.read_csv('./goden_full_raw.csv')
df.shape

/home/shj16110/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,3,4,5,6,748,749,750,751,753,754,755,756,757,759,760,761,762,763,764,767,768,770,771,772,773,774,776,777,778,779,780,781,782) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(46022, 785)

In [3]:
pd.options.display.max_columns=100
df.head(3)

,username,fname.gender,username_split_predict,last,last_two,first,first2,nchar,vowels.pct,digits.pct,last_is_vowel,first_is_vowel,last_is_digit,first_is_digit,digits.num,upper.pct,first_is_upper,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,...,feature_718,feature_719,feature_720,feature_721,feature_722,feature_723,feature_724,feature_725,feature_726,feature_727,feature_728,feature_729,feature_730,about.avatar,about.avatar_cdn,about.avatar_large,about.avatar_large_cdn,about.chosen_role,about.company,about.corporate,about.cover_image,about.display_name,about.hourly_rate,about.id,about.location,about.preferred_freelancer,about.primary_currency,about.primary_language,about.profile_description,about.public_name,about.recommendations,about.registration_date,about.registration_date_human,about.reputation,about.role,about.status,about.tagline,about.timezone,about.username,about.username_sentence,hourlyRate,resume.certifications,resume.education,resume.exams,resume.experience,resume.publications,resume.show,skills,timeOffset,userId
0,a1anm,male,male,m,nm,a,a1,5,0.400000,0.200000,False,True,False,False,1,0,False,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,13.0,4.0,/img/unknown.png,//cdn6.f-cdn.com/img/unknown.png,/img/unknown.png,//cdn6.f-cdn.com/img/unknown.png,3.0,NaN,None,{u'current_image': {u'url': u'//cdn2.f-cdn.com...,a1anm,None,897638.0,"{u'administrative_area': None, u'city': u'Ball...",False,"{u'code': u'USD', u'name': u'US Dollar', u'cou...",en,NaN,a1anm,0.0,1.229565e+09,"December, 2008","{u'user_id': 897638, u'last3months': {u'comple...",1.0,"{u'payment_verified': True, u'identity_verifie...",NaN,"{u'country': u'UK', u'offset': 1, u'id': 262, ...",a1anm,A1anm,5.0,[],[],[],[],[],False,[],0.0,897638.0
1,a1myspace,male,unknow,e,ce,a,a1,9,0.444444,0.111111,True,True,False,False,1,0,False,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,7.0,0.0,7.0,0.0,8.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,8.0,/img/unknown.png,//cdn6.f-cdn.com/img/unknown.png,/img/unknown.png,//cdn6.f-cdn.com/img/unknown.png,3.0,a1myspace,None,{u'current_image': {u'url': u'//cdn2.f-cdn.com...,a1myspace,None,223120.0,"{u'administrative_area': None, u'city': u'Turr...",False,"{u'code': u'USD', u'name': u'US Dollar', u'cou...",en,NaN,a1myspace,0.0,1.151814e+09,"July, 2006","{u'user_id': 223120, u'last3months': {u'comple...",1.0,"{u'payment_verified': False, u'identity_verifi...",NaN,"{u'country': u'AU', u'offset': 10, u'id': 422,...",a1myspace,A1myspace,10.0,[],[],[],[],[],False,"[{u'usages': 0, u'seo_url': u'php', u'islocal'...",660.0,223120.0
2,a1xdotcom,male,female,m,om,a,a1,9,0.333333,0.111111,False,True,False,False,1,0,False,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,6.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,14.0,8.0,/img/unknown.png,//cdn6.f-cdn.com/img/unknown.png,/img/unknown.png,//cdn6.f-cdn.com/img/unknown.png,3.0,A1x.com,None,{u'current_image': {u'url': u'//cdn2.f-cdn.com...,a1xdotcom,None,1765704.0,"{u'administrative_area': None, u'city': u'Litt...",False,"{u'code': u'USD', u'name': u'US Dollar', u'cou...",en,NaN,a1xdotcom,0.0,1.282742e+09,"August, 2010","{u'user_id': 1765704, u'last3months': {u'compl...",1.0,"{u'payment_verified': False, u'identity_verifi...",NaN,"{u'country': u'US', u'offset': -5, u'id': 81, ...",a1xdotcom,A1xdotcom,20.0,[],[],[],[],[],False,[],-300.0,1765704.0

In [6]:
df.columns[-40:]

Index([u'feature_728', u'feature_729', u'feature_730', u'about.avatar',
       u'about.avatar_cdn', u'about.avatar_large', u'about.avatar_large_cdn',
       u'about.chosen_role', u'about.company', u'about.corporate',
       u'about.cover_image', u'about.display_name', u'about.hourly_rate',
       u'about.id', u'about.location', u'about.preferred_freelancer',
       u'about.primary_currency', u'about.primary_language',
       u'about.profile_description', u'about.public_name',
       u'about.recommendations', u'about.registration_date',
       u'about.registration_date_human', u'about.reputation', u'about.role',
       u'about.status', u'about.tagline', u'about.timezone', u'about.username',
       u'about.username_sentence', u'hourlyRate', u'resume.certifications',
       u'resume.education', u'resume.exams', u'resume.experience',
       u'resume.publications', u'resume.show', u'skills', u'timeOffset',
       u'userId'],
      dtype='object')

In [8]:
df1 = df.drop(['about.avatar', u'about.avatar_cdn', u'about.avatar_large',
       u'about.avatar_large_cdn', u'about.cover_image', u'about.id', u'userId',
                'about.corporate', 'about.preferred_freelancer', 
                ], axis=1)

In [9]:
df1['Month'] = df1['about.registration_date_human'].fillna('NoMn, NoYr').apply(lambda x: x.split(',')[0] )
df1['Year'] = df1['about.registration_date_human'].fillna('NoMn, NoYr').apply(lambda x: x.split(',')[1] )

df1['about.location'] = df1['about.location'].fillna("")

In [10]:
def helperD(x):
    try:
        return literal_eval(x)
    except:
        return {}
    
def select1(x):
    try: 
        return x['city']
    except:
        return ""
    
        
def select2(x):
    try: 
        return x['country']['name']
    except:
        return ""

In [13]:
df1['city'] = df1['about.location'].apply(helperD).apply(select1)
df1['country'] = df1['about.location'].apply(helperD).apply(select2)

In [ ]:
df1.drop(['about.registration_date_human','about.registration_date_human',
          'about.location','about.profile_description'], axis=1)

In [15]:
df1.head(1)

,username,fname.gender,username_split_predict,last,last_two,first,first2,nchar,vowels.pct,digits.pct,last_is_vowel,first_is_vowel,last_is_digit,first_is_digit,digits.num,upper.pct,first_is_upper,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,...,feature_713,feature_714,feature_715,feature_716,feature_717,feature_718,feature_719,feature_720,feature_721,feature_722,feature_723,feature_724,feature_725,feature_726,feature_727,feature_728,feature_729,feature_730,about.chosen_role,about.company,about.display_name,about.hourly_rate,about.location,about.primary_currency,about.primary_language,about.profile_description,about.public_name,about.recommendations,about.registration_date,about.registration_date_human,about.reputation,about.role,about.status,about.tagline,about.timezone,about.username,about.username_sentence,hourlyRate,resume.certifications,resume.education,resume.exams,resume.experience,resume.publications,resume.show,skills,timeOffset,Month,Year,city,country
0,a1anm,male,male,m,nm,a,a1,5,0.4,0.2,False,True,False,False,1,0,False,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,13.0,4.0,3.0,NaN,a1anm,None,"{u'administrative_area': None, u'city': u'Ball...","{u'code': u'USD', u'name': u'US Dollar', u'cou...",en,NaN,a1anm,0.0,1.229565e+09,"December, 2008","{u'user_id': 897638, u'last3months': {u'comple...",1.0,"{u'payment_verified': True, u'identity_verifie...",NaN,"{u'country': u'UK', u'offset': 1, u'id': 262, ...",a1anm,A1anm,5.0,[],[],[],[],[],False,[],0.0,December,2008,Ballymena,United Kingdom

In [22]:
df1['about.reputation'].isnull().sum()

11803

In [23]:
df1['about.reputation'] = df1['about.reputation'].fillna("")

In [27]:
df1['about.reputation'].apply(helperD).apply(len).value_counts()

9    34219
0    11803
Name: about.reputation, dtype: int64

In [49]:
a = df1['about.reputation'].apply(helperD)

In [52]:
import re

In [48]:
df['about.status'].value_counts()

{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}       22450
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}         4153
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}          3413
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}         1079
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}            744
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}        470
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': False}        394
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}           386
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}          341
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}           200
{u'payment_verified': True, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            136
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': False}          93
{u'payment_verified': True, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}              81
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': False}           61
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}          48
{u'payment_verified': False, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            41
{u'payment_verified': False, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}             25
{u'payment_verified': False, u'identity_verified': False, u'email_verified': False, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}         15
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': False}          13
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}          12
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': False}            11
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}           10
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            7
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': False}            6
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}             5
{u'payment_verified': True, u'identity_verified': True, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}             4
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': False}            4
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}           3
{u'payment_verified': False, u'identity_verified': True, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}             3
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': False}           2
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': False}          2
{u'payment_verified': False, u'identity_verified': True, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            2
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}            1
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': False}         1
{u'payment_verified': False, u'identity_verified': False, u'email_verified': False, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': False}        1
{u'payment_verified': True, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}              1
{u'payment_verified': True, u'identity_verified': False, u'email_verified': False, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            1
Name: about.status, dtype: int64

In [35]:
df1['resume.show'].value_counts()

False    32240
True      1979
Name: resume.show, dtype: int64

In [39]:
df1['about.primary_currency'].value_counts()

{u'code': u'USD', u'name': u'US Dollar', u'country': u'US', u'sign': u'$', u'exchange_rate': 1, u'id': 1}                      32769
{u'code': u'GBP', u'name': u'British Pounds', u'country': u'UK', u'sign': u'\xa3', u'exchange_rate': 1.307651, u'id': 4}         428
{u'code': u'EUR', u'name': u'Euro', u'country': u'EU', u'sign': u'\u20ac', u'exchange_rate': 1.16075, u'id': 8}                  371
{u'code': u'AUD', u'name': u'Australian Dollar', u'country': u'AU', u'sign': u'$', u'exchange_rate': 0.7649, u'id': 3}           274
{u'code': u'INR', u'name': u'Indian Rupee', u'country': u'IN', u'sign': u'\u20b9', u'exchange_rate': 0.015455, u'id': 11}        121
{u'code': u'CAD', u'name': u'Canadian Dollar', u'country': u'CA', u'sign': u'$', u'exchange_rate': 0.783484, u'id': 9}           119
{u'code': u'SGD', u'name': u'Singapore Dollar', u'country': u'SG', u'sign': u'$', u'exchange_rate': 0.732654, u'id': 6}           30
{u'code': u'NZD', u'name': u'New Zealand Dollar', u'country': u'NZ', u'sign': u'$', u'exchange_rate': 0.690751, u'id': 2}         25
{u'code': u'PHP', u'name': u'Philippine Peso', u'country': u'PH', u'sign': u'\u20b1', u'exchange_rate': 0.019507, u'id': 7}       15
{u'code': u'ZAR', u'name': u'South African Rand', u'country': u'ZA', u'sign': u'R', u'exchange_rate': 0.070305, u'id': 10}        12
{u'code': u'MXN', u'name': u'Mexican Peso', u'country': u'MX', u'sign': u'$', u'exchange_rate': 0.052071, u'id': 14}               8
{u'code': u'HKD', u'name': u'HongKong Dollar', u'country': u'HK', u'sign': u'$', u'exchange_rate': 0.128168, u'id': 5}             8
{u'code': u'PLN', u'name': u'Polish Zloty', u'country': u'PL', u'sign': u'z\u0142', u'exchange_rate': 0.273519, u'id': 19}         7
{u'code': u'ARS', u'name': u'Argentine Peso', u'country': u'AR', u'sign': u'$', u'exchange_rate': 0.056705, u'id': 25}             6
{u'code': u'SEK', u'name': u'Swedish Krona', u'country': u'SE', u'sign': u'kr', u'exchange_rate': 0.11858, u'id': 17}              5
{u'code': u'MYR', u'name': u'Malaysian Ringgit', u'country': u'MY', u'sign': u'RM', u'exchange_rate': 0.23607, u'id': 16}          5
{u'code': u'BRL', u'name': u'Brazilian Real', u'country': u'BR', u'sign': u'R$', u'exchange_rate': 0.301777, u'id': 20}            4
{u'code': u'IDR', u'name': u'Indonesian Rupiah', u'country': u'ID', u'sign': u'Rp', u'exchange_rate': 7.4e-05, u'id': 15}          3
{u'code': u'CNY', u'name': u'Chinese Yuan', u'country': u'CN', u'sign': u'\uffe5', u'exchange_rate': 0.15071, u'id': 21}           3
{u'code': u'JMD', u'name': u'Jamaican Dollar', u'country': u'JM', u'sign': u'$', u'exchange_rate': 0.007864, u'id': 12}            2
{u'code': u'JPY', u'name': u'Japanese Yen', u'country': u'JP', u'sign': u'\xa5', u'exchange_rate': 0.008768, u'id': 18}            2
{u'code': u'CLP', u'name': u'Chilean Peso', u'country': u'CL', u'sign': u'$', u'exchange_rate': 0.001576, u'id': 13}               1
{u'code': u'VND', u'name': u'Vietnamese Dong', u'country': u'VN', u'sign': u'\u20ab', u'exchange_rate': 4.4e-05, u'id': 23}        1
Name: about.primary_currency, dtype: int64

In [41]:
df1['about.role'].value_counts()

1.0    31578
0.0     2641
Name: about.role, dtype: int64

In [42]:
df1['about.status'].value_counts()

{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}       22450
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}         4153
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}          3413
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}         1079
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}            744
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}        470
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': False}        394
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}           386
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}          341
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}           200
{u'payment_verified': True, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            136
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': False}          93
{u'payment_verified': True, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}              81
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': False}           61
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}          48
{u'payment_verified': False, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            41
{u'payment_verified': False, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}             25
{u'payment_verified': False, u'identity_verified': False, u'email_verified': False, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}         15
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': False}          13
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}          12
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': False}            11
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}           10
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            7
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': False}            6
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}             5
{u'payment_verified': True, u'identity_verified': True, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}             4
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': False}            4
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': True}           3
{u'payment_verified': False, u'identity_verified': True, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': True, u'profile_complete': True}             3
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': False}           2
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': False}          2
{u'payment_verified': False, u'identity_verified': True, u'email_verified': True, u'deposit_made': False, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            2
{u'payment_verified': True, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}            1
{u'payment_verified': False, u'identity_verified': False, u'email_verified': True, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': False}         1
{u'payment_verified': False, u'identity_verified': False, u'email_verified': False, u'deposit_made': False, u'phone_verified': False, u'facebook_connected': False, u'profile_complete': False}        1
{u'payment_verified': True, u'identity_verified': True, u'email_verified': True, u'deposit_made': True, u'phone_verified': False, u'facebook_connected': True, u'profile_complete': True}              1
{u'payment_verified': True, u'identity_verified': False, u'email_verified': False, u'deposit_made': True, u'phone_verified': True, u'facebook_connected': False, u'profile_complete': True}            1
Name: about.status, dtype: int64

In [45]:
df['about.timezone'].value_counts()

{u'country': u'US', u'offset': -5, u'id': 81, u'timezone': u'America/Chicago'}                   6715
{u'country': u'UK', u'offset': 1, u'id': 262, u'timezone': u'Europe/London'}                     3973
{u'country': u'US', u'offset': -4, u'id': 120, u'timezone': u'America/New_York'}                 3779
{u'country': u'US', u'offset': -7, u'id': 105, u'timezone': u'America/Los_Angeles'}              3682
{u'country': u'IN', u'offset': 5.5, u'id': 403, u'timezone': u'Asia/Kolkata'}                    1098
{u'country': u'CA', u'offset': -4, u'id': 384, u'timezone': u'America/Toronto'}                   958
{u'country': u'US', u'offset': -6, u'id': 86, u'timezone': u'America/Denver'}                     880
{u'country': u'US', u'offset': -7, u'id': 123, u'timezone': u'America/Phoenix'}                   777
{u'country': u'AU', u'offset': 10, u'id': 422, u'timezone': u'Australia/Sydney'}                  607
{u'country': u'DE', u'offset': 2, u'id': 245, u'timezone': u'Europe/Berlin'}                      501
{u'country': u'CA', u'offset': -7, u'id': 145, u'timezone': u'America/Vancouver'}                 418
{u'country': u'SG', u'offset': 8, u'id': 210, u'timezone': u'Asia/Singapore'}                     388
{u'country': u'NL', u'offset': 2, u'id': 241, u'timezone': u'Europe/Amsterdam'}                   387
{u'country': u'IT', u'offset': 2, u'id': 275, u'timezone': u'Europe/Rome'}                        374
{u'country': u'IN', u'offset': 5.5, u'id': 164, u'timezone': u'Asia/Calcutta'}                    357
{u'country': u'IE', u'offset': 1, u'id': 252, u'timezone': u'Europe/Dublin'}                      332
{u'country': u'IL', u'offset': 3, u'id': 180, u'timezone': u'Asia/Jerusalem'}                     296
{u'country': u'FR', u'offset': 2, u'id': 271, u'timezone': u'Europe/Paris'}                       283
{u'country': u'ES', u'offset': 2, u'id': 264, u'timezone': u'Europe/Madrid'}                      276
{u'country': u'AU', u'offset': 10, u'id': 412, u'timezone': u'Australia/Brisbane'}                275
{u'country': u'PK', u'offset': 5, u'id': 183, u'timezone': u'Asia/Karachi'}                       274
{u'country': u'AU', u'offset': 10, u'id': 420, u'timezone': u'Australia/Melbourne'}               272
{u'country': u'SE', u'offset': 2, u'id': 282, u'timezone': u'Europe/Stockholm'}                   248
{u'country': u'PH', u'offset': 8, u'id': 192, u'timezone': u'Asia/Manila'}                        217
{u'country': u'HK', u'offset': 8, u'id': 175, u'timezone': u'Asia/Hong_Kong'}                     216
{u'country': u'NZ', u'offset': 12, u'id': 306, u'timezone': u'Pacific/Auckland'}                  209
{u'country': u'MY', u'offset': 8, u'id': 186, u'timezone': u'Asia/Kuala_Lumpur'}                  192
{u'country': u'DK', u'offset': 2, u'id': 251, u'timezone': u'Europe/Copenhagen'}                  191
{u'country': u'US', u'offset': -4, u'id': 349, u'timezone': u'America/Indiana/Indianapolis'}      188
{u'country': u'CH', u'offset': 2, u'id': 294, u'timezone': u'Europe/Zurich'}                      185
                                                                                                 ...
{u'country': u'ME', u'offset': 2, u'id': 272, u'timezone': u'Europe/Podgorica'}                     1
{u'country': u'TK', u'offset': 13, u'id': 309, u'timezone': u'Pacific/Fakaofo'}                     1
{u'country': u'LY', u'offset': 2, u'id': 49, u'timezone': u'Africa/Tripoli'}                        1
{u'country': u'DJ', u'offset': 3, u'id': 20, u'timezone': u'Africa/Djibouti'}                       1
{u'country': u'SL', u'offset': 0, u'id': 22, u'timezone': u'Africa/Freetown'}                       1
{u'country': u'MW', u'offset': 2, u'id': 11, u'timezone': u'Africa/Blantyre'}                       1
{u'country': u'LR', u'offset': 0, u'id': 41, u'timezone': u'Africa/Monrovia'}                       1
{u'country': u'KN', u'offset': -4, u'id': 137, u'timezone': u'America/St_Kitts'}                    1
{u'country': u'AR', u'offset': -3, u'id': 65, u'timezone': u'America/Argentina/San_Luis'}           1
{u'country': u'AR', u'offset': -3, u'id': 62, u'timezone': u'America/Argentina/Rio_Gallegos'}       1
{u'country': u'UZ', u'offset': 5, u'id': 207, u'timezone': u'Asia/Samarkand'}                       1
{u'country': u'RU', u'offset': 10, u'id': 206, u'timezone': u'Asia/Sakhalin'}                       1
{u'country': u'TD', u'offset': 1, u'id': 43, u'timezone': u'Africa/Ndjamena'}                       1
{u'country': u'VC', u'offset': -4, u'id': 140, u'timezone': u'America/St_Vincent'}                  1
{u'country': u'PF', u'offset': -9.5, u'id': 316, u'timezone': u'Pacific/Marquesas'}                 1
{u'country': u'GW', u'offset': 0, u'id': 10, u'timezone': u'Africa/Bissau'}                         1
{u'country': u'RU', u'offset': 8, u'id': 176, u'timezone': u'Asia/Irkutsk'}                         1
{u'country': u'GE', u'offset': 4, u'id': 213, u'timezone': u'Asia/Tbilisi'}                         1
{u'country': u'LA', u'offset': 7, u'id': 218, u'timezone': u'Asia/Vientiane'}                       1
{u'country': u'MN', u'offset': 9, u'id': 407, u'timezone': u'Asia/Ulaanbaatar'}                     1
{u'country': u'AR', u'offset': -3, u'id': 61, u'timezone': u'America/Argentina/Mendoza'}            1
{u'country': u'PG', u'offset': 10, u'id': 323, u'timezone': u'Pacific/Port_Moresby'}                1
{u'country': u'GG', u'offset': 1, u'id': 254, u'timezone': u'Europe/Guernsey'}                      1
{u'country': u'PS', u'offset': 3, u'id': 173, u'timezone': u'Asia/Gaza'}                            1
{u'country': u'CA', u'offset': -7, u'id': 344, u'timezone': u'America/Dawson_Creek'}                1
{u'country': u'TC', u'offset': -4, u'id': 92, u'timezone': u'America/Grand_Turk'}                   1
{u'country': u'FJ', u'offset': 12, u'id': 310, u'timezone': u'Pacific/Fiji'}                        1
{u'country': u'CN', u'offset': 8, u'id': 174, u'timezone': u'Asia/Harbin'}                          1
{u'country': u'MZ', u'offset': 2, u'id': 37, u'timezone': u'Africa/Maputo'}                         1
{u'country': u'BR', u'offset': -4, u'id': 74, u'timezone': u'America/Boa_Vista'}                    1
Name: about.timezone, Length: 270, dtype: int64

In [47]:
df['timeOffset'].value_counts()

-300.0    6899
-240.0    5201
-420.0    4994
 0.0      4584
 60.0     3461
 330.0    1484
 660.0    1280
 480.0    1245
-360.0    1181
 120.0    1166
 600.0     374
 180.0     364
 420.0     323
 300.0     299
-180.0     299
 780.0     211
 240.0     176
 360.0     173
 540.0     133
 630.0      94
-480.0      84
-600.0      69
-120.0      65
 345.0      13
-660.0      11
-150.0       7
 210.0       5
 570.0       5
 825.0       4
 270.0       4
 390.0       3
 720.0       3
 510.0       2
-60.0        2
-570.0       1
Name: timeOffset, dtype: int64