In [3]:
import shutil
import os

In [19]:
pwd

u'/home/soyoung/face/prepared_baidu_faces'

In [20]:
path = '/home/soyoung/face/prepared_baidu_faces/'

In [21]:
folders = os.listdir(path)
folders = [i for i in folders if i.startswith('set')]
len(folders)

28

In [22]:
print folders

['set_0_V96', 'set_11_V96', 'set_1_V96', 'set_9_V96', 'set_23_V96', 'set_24_V96', 'set_26_V96', 'set_14_V96', 'set_16_V96', 'set_18_V96', 'set_21_V96', 'set_8_V96', 'set_13_V96', 'set_7_V96', 'set_15_V96', 'set_25_V96', 'set_17_V96', 'set_19_V96', 'set_6_V96', 'set_5_V96', 'set_3_V96', 'set_2_V96', 'set_22_V96', 'set_12_V96', 'set_27_V96', 'set_20_V96', 'set_10_V96', 'set_4_V96']

In [29]:
for i in folders:
    for j in os.listdir(i):
        try:
            shutil.move(path+i+'/'+j, path)
        except:
            print i,j

set_11_V96 sub_46

In [30]:
new = os.listdir('.')
len(new)

119

In [34]:
import pandas as pd

In [37]:
df = pd.DataFrame(new, columns=['name'])
df = df.sort_values('name')
df

                     name
90     .ipynb_checkpoints
82                  east1
37                  east2
35                 euroB1
67                 euroB2
39                 euroG1
60                 euroG2
31   mv_from_folder.ipynb
8                   sub_1
91                 sub_10
9                 sub_100
68                sub_101
96                sub_102
112               sub_103
22                sub_104
32                sub_105
109               sub_106
101               sub_107
4                 sub_108
84                sub_109
13                 sub_11
15                sub_110
80                sub_111
40                 sub_12
93                 sub_13
107                sub_14
65                 sub_15
12                 sub_16
118                sub_17
41                 sub_18
..                    ...
36                 sub_72
29                 sub_73
73                 sub_74
11                 sub_75
108                sub_76
64                 sub_77
88                 sub_78
71                 sub_79
99                  sub_8
10                 sub_80
3                  sub_81
98                 sub_82
86                 sub_83
83                 sub_84
17                 sub_85
62                 sub_86
66                 sub_87
100                sub_88
81                 sub_89
89                  sub_9
45                 sub_90
114                sub_91
6                  sub_92
30                 sub_93
56                 sub_94
52                 sub_95
16                 sub_96
92                 sub_97
7                  sub_98
54                 sub_99

[119 rows x 1 columns]