In [1]:
import pandas as pd
import os
import shutil

# import sys
# reload(sys)
# sys.setdefaultencoding('utf8')

In [2]:
os.getcwd()

'/home/soyoung/face/baidu_face_project/96_data/batch1Data'

In [5]:
path = '/home/soyoung/face/baidu_face_project/batch2Data/'

In [6]:
df = pd.read_csv(path+'labels.csv', names=['id','url'])
df.shape

(90711, 2)

In [7]:
df.head()

   id                                                url
0   1  /home/face/prepared_baidu_faces_cp/sub_101/o_2...
1   1  /home/face/prepared_baidu_faces_cp/sub_101/p1_...
2   1  /home/face/prepared_baidu_faces_cp/sub_101/OT2...
3   1  /home/face/prepared_baidu_faces_cp/sub_101/oYY...
4   1  /home/face/prepared_baidu_faces_cp/sub_101/OOO...

In [8]:
data = pd.read_csv(path+'reps.csv', header=None)
data.shape

(90711, 128)

In [9]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,118,119,120,121,122,123,124,125,126,127
0,0.052561,0.000391,-0.056738,0.141174,0.027441,0.049612,0.030643,0.007977,0.033394,0.018895,...,0.074585,0.204278,-0.035850,0.016196,-0.109116,0.136961,0.095081,0.022277,0.027073,0.099842
1,0.004180,0.191736,0.081938,0.131037,-0.017847,0.093564,0.027027,0.025474,0.071489,0.059691,...,0.073242,0.038770,0.041488,0.088541,-0.026927,0.143638,0.231782,-0.102136,0.176223,0.090192
2,0.035473,-0.078845,-0.130248,-0.004106,0.108466,0.002791,0.043736,0.007019,-0.132781,0.007908,...,0.033989,0.129211,-0.108007,0.002534,-0.010056,0.108730,-0.153669,0.041176,-0.168276,0.016441
3,0.109629,-0.023703,0.022950,0.042831,0.109145,0.071201,0.059694,0.060945,0.046343,-0.170765,...,0.077519,0.138939,-0.005553,0.108416,-0.091536,0.087762,0.096681,-0.006892,0.073456,0.019049
4,0.092153,-0.034413,-0.077425,0.056193,0.098403,-0.019449,0.039712,-0.005715,0.079965,-0.085981,...,0.001492,0.166045,-0.031930,0.187724,-0.001866,0.190012,0.054177,-0.027545,-0.029409,-0.103086

In [10]:
data['url']=df['url']
data.shape

(90711, 129)

In [11]:
del df
df = data

In [12]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,url
0,0.052561,0.000391,-0.056738,0.141174,0.027441,0.049612,0.030643,0.007977,0.033394,0.018895,...,0.204278,-0.035850,0.016196,-0.109116,0.136961,0.095081,0.022277,0.027073,0.099842,/home/face/prepared_baidu_faces_cp/sub_101/o_2...
1,0.004180,0.191736,0.081938,0.131037,-0.017847,0.093564,0.027027,0.025474,0.071489,0.059691,...,0.038770,0.041488,0.088541,-0.026927,0.143638,0.231782,-0.102136,0.176223,0.090192,/home/face/prepared_baidu_faces_cp/sub_101/p1_...
2,0.035473,-0.078845,-0.130248,-0.004106,0.108466,0.002791,0.043736,0.007019,-0.132781,0.007908,...,0.129211,-0.108007,0.002534,-0.010056,0.108730,-0.153669,0.041176,-0.168276,0.016441,/home/face/prepared_baidu_faces_cp/sub_101/OT2...
3,0.109629,-0.023703,0.022950,0.042831,0.109145,0.071201,0.059694,0.060945,0.046343,-0.170765,...,0.138939,-0.005553,0.108416,-0.091536,0.087762,0.096681,-0.006892,0.073456,0.019049,/home/face/prepared_baidu_faces_cp/sub_101/oYY...
4,0.092153,-0.034413,-0.077425,0.056193,0.098403,-0.019449,0.039712,-0.005715,0.079965,-0.085981,...,0.166045,-0.031930,0.187724,-0.001866,0.190012,0.054177,-0.027545,-0.029409,-0.103086,/home/face/prepared_baidu_faces_cp/sub_101/OOO...

In [13]:
df['full_url']=df['url'].apply(lambda x: '/home/soyoung/face/baidu_full_pics'+x.split('prepared_baidu_faces')[-1][:-3]+'jpg')
df.shape

(90711, 130)

In [14]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,120,121,122,123,124,125,126,127,url,full_url
0,0.052561,0.000391,-0.056738,0.141174,0.027441,0.049612,0.030643,0.007977,0.033394,0.018895,...,-0.035850,0.016196,-0.109116,0.136961,0.095081,0.022277,0.027073,0.099842,/home/face/prepared_baidu_faces_cp/sub_101/o_2...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...
1,0.004180,0.191736,0.081938,0.131037,-0.017847,0.093564,0.027027,0.025474,0.071489,0.059691,...,0.041488,0.088541,-0.026927,0.143638,0.231782,-0.102136,0.176223,0.090192,/home/face/prepared_baidu_faces_cp/sub_101/p1_...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...
2,0.035473,-0.078845,-0.130248,-0.004106,0.108466,0.002791,0.043736,0.007019,-0.132781,0.007908,...,-0.108007,0.002534,-0.010056,0.108730,-0.153669,0.041176,-0.168276,0.016441,/home/face/prepared_baidu_faces_cp/sub_101/OT2...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...
3,0.109629,-0.023703,0.022950,0.042831,0.109145,0.071201,0.059694,0.060945,0.046343,-0.170765,...,-0.005553,0.108416,-0.091536,0.087762,0.096681,-0.006892,0.073456,0.019049,/home/face/prepared_baidu_faces_cp/sub_101/oYY...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...
4,0.092153,-0.034413,-0.077425,0.056193,0.098403,-0.019449,0.039712,-0.005715,0.079965,-0.085981,...,-0.031930,0.187724,-0.001866,0.190012,0.054177,-0.027545,-0.029409,-0.103086,/home/face/prepared_baidu_faces_cp/sub_101/OOO...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...

In [15]:
df['name']=df['full_url'].apply(lambda x:x.split('/home/soyoung/face/baidu_full_pics_cp/')[-1])
df.shape

(90711, 131)

In [16]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,121,122,123,124,125,126,127,url,full_url,name
0,0.052561,0.000391,-0.056738,0.141174,0.027441,0.049612,0.030643,0.007977,0.033394,0.018895,...,0.016196,-0.109116,0.136961,0.095081,0.022277,0.027073,0.099842,/home/face/prepared_baidu_faces_cp/sub_101/o_2...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...,sub_101/o_285821159850.jpg
1,0.004180,0.191736,0.081938,0.131037,-0.017847,0.093564,0.027027,0.025474,0.071489,0.059691,...,0.088541,-0.026927,0.143638,0.231782,-0.102136,0.176223,0.090192,/home/face/prepared_baidu_faces_cp/sub_101/p1_...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...,sub_101/p1_s(1).jpg
2,0.035473,-0.078845,-0.130248,-0.004106,0.108466,0.002791,0.043736,0.007019,-0.132781,0.007908,...,0.002534,-0.010056,0.108730,-0.153669,0.041176,-0.168276,0.016441,/home/face/prepared_baidu_faces_cp/sub_101/OT2...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...,sub_101/OT20140801222157219.jpg
3,0.109629,-0.023703,0.022950,0.042831,0.109145,0.071201,0.059694,0.060945,0.046343,-0.170765,...,0.108416,-0.091536,0.087762,0.096681,-0.006892,0.073456,0.019049,/home/face/prepared_baidu_faces_cp/sub_101/oYY...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...,sub_101/oYYBAFS_NrWIbbeeAAM8pdjlWM8AACPZwCk2Us...
4,0.092153,-0.034413,-0.077425,0.056193,0.098403,-0.019449,0.039712,-0.005715,0.079965,-0.085981,...,0.187724,-0.001866,0.190012,0.054177,-0.027545,-0.029409,-0.103086,/home/face/prepared_baidu_faces_cp/sub_101/OOO...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...,sub_101/OOOPIC_shjl1234_200909254abba111aeebca...

In [17]:
for i in df['full_url']:
    print i
    break

/home/soyoung/face/baidu_full_pics_cp/sub_101/o_285821159850.jpg

In [19]:
dest = '/home/soyoung/face/baidu_full_pics/hasFace/'

In [20]:
source = '/home/soyoung/face/baidu_full_pics/'

In [34]:
# for i in range(112):
#     try:
#         os.mkdir(dest+'sub_'+str(i))
#     except:
#         pass

In [21]:
n=0
no=[]
for i in df['name']:
    try:
        shutil.move(source+i, dest+i)
    except Exception as e:
        n+=1
        no.append(i)
#         print '!',
n

1408

In [22]:
n=0
no=[]
for i in df['name']:
    try:
        shutil.move(source+i[:-3]+'JPG', dest+i)
    except Exception as e:
        n+=1
        no.append(i)
#         print '!',
n

89472

In [23]:
# nodf=pd.DataFrame(no, columns=['name'])
# nodf

In [24]:
n=0
no=[]
for i in df['name']:
    try:
        shutil.move(dest+i, dest+i)
    except Exception as e:
        n+=1
        no.append(i)
#         print '!',
n

169

In [26]:
no[:10]

['sub_101/P1200079_\xb8\xb1\xb1\xbe.jpg',
 'sub_65/5744_\xc6\xd5\xb7\xa8\xb9\xa4\xd7\xf7\xc8\xcb\xd4\xb1\xce\xaa\xd1\xa7\xc9\xfa\xc9\xa2\xb7\xa2\xd0\xfb\xb4\xab\xb2\xc4\xc1\xcf\xcf\xd6\xb3\xa1.jpg',
 'sub_111/\xe8\xd6\xd4\xc2\xa4\xa2\xa4\xa4ABP-308.jpg',
 'sub_111/\xba\xa3\xd0\xc5\xb5\xe7\xc6\xf7\xc5\xb7\xd6\xde\xcd\xf8\xd5\xbe\xb8\xc4\xb0\xe607.jpg',
 'sub_111/\xdf\xc7\xb2\xc1\xd5\xd5\xcf\xe0\xb9\xdd.jpg',
 'sub_111/\xb1\xb1\xc3\xc0\xc7\xd9\xc9\xe7\xb9\xc5\xc7\xd9\xbc\xd2\xcd\xf5\xb7\xc6\xb2\xce\xb9\xdb\xd7\xc1\xc7\xd9\xcc\xc3 023.jpg',
 'sub_111/\xb9\xc4\xd5\xc6\xb5\xc4\xc9\xcc\xce\xf1\xc8\xcb\xca\xbfppt\xb1\xb3\xbe\xb0\xcd\xbc\xc6\xac.jpg',
 'sub_111/\xbb\xc6\xca\xa5\xd2\xc0\xd0\xd4\xb8\xd0 (4).jpg',
 'sub_111/\xc9\xd9\xca\xfd\xc3\xf1\xd7\xe5\xc8\xcb\xce\xef\xd3\xcd\xbb\xad.jpg',
 'sub_111/\xd0\xbb\xb0\xb2\xe7\xf7.jpg']

In [27]:
df.tail()

,0,1,2,3,4,5,6,7,8,9,...,121,122,123,124,125,126,127,url,full_url,name
90706,0.003517,0.052479,-0.044540,0.089930,-0.028029,0.054476,0.062636,0.098270,0.111579,0.009150,...,0.021647,-0.102794,0.188510,-0.030728,-0.013842,-0.047551,0.039203,/home/face/prepared_baidu_faces_cp/sub_17/1397...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/13977132_597663.jpg
90707,0.030297,0.122150,-0.020289,0.030955,-0.067142,0.080773,0.100250,0.113896,-0.048586,0.022922,...,-0.029517,-0.004100,0.079527,0.006152,-0.015773,-0.028892,0.031459,/home/face/prepared_baidu_faces_cp/sub_17/1379...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/13799170921005952220031f9e06.jpg
90708,0.108930,-0.036421,-0.151056,0.065437,0.151416,-0.022955,0.069124,-0.000841,-0.000843,0.038638,...,0.119045,-0.076127,0.176795,-0.043373,-0.035653,-0.147453,-0.066531,/home/face/prepared_baidu_faces_cp/sub_17/1377...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/137795874348208_0.jpg
90709,0.076546,0.111801,-0.102897,0.136395,0.015714,0.078710,0.012302,0.009330,0.018362,0.073968,...,0.040410,-0.044080,0.179863,0.141644,-0.070568,0.029913,0.046886,/home/face/prepared_baidu_faces_cp/sub_17/1388...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/1388629689373.jpg
90710,0.095205,0.065115,-0.086386,0.142298,0.062028,0.032015,0.062714,0.025182,0.039111,0.017706,...,0.063335,-0.122442,0.203849,0.049614,-0.047644,-0.030951,0.004675,/home/face/prepared_baidu_faces_cp/sub_17/1388...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/1388471374472.jpg

In [28]:
!pwd

/home/soyoung/face/baidu_face_project/96_data/batch1Data

In [30]:
NotWant = df[df['name'].apply(lambda x: x in no)]
NotWant.shape

(169, 131)

In [31]:
NotWant.head()

,0,1,2,3,4,5,6,7,8,9,...,121,122,123,124,125,126,127,url,full_url,name
60,0.101504,-0.021542,0.036340,0.001354,0.158605,0.217536,0.084382,0.051548,-0.023561,-0.069725,...,0.034167,0.064979,0.108510,-0.014202,0.001783,0.081068,0.033168,/home/face/prepared_baidu_faces_cp/sub_101/P12...,/home/soyoung/face/baidu_full_pics_cp/sub_101/...,sub_101/P1200079_ï¿½ï¿½ï¿½ï¿½.jpg
17132,0.037967,0.096498,0.107351,0.098461,0.001813,0.212054,-0.078043,-0.010327,-0.012693,-0.030228,...,-0.022751,0.020324,-0.029052,0.191113,0.008173,0.247886,0.144030,/home/face/prepared_baidu_faces_cp/sub_65/5744...,/home/soyoung/face/baidu_full_pics_cp/sub_65/5...,sub_65/5744_ï¿½Õ·ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô±ÎªÑ§ï¿½ï¿½É¢ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö³ï¿½.jpg
21728,0.062408,-0.013088,-0.109287,0.148724,0.115410,-0.007249,0.118385,0.007383,-0.008671,-0.016104,...,0.111333,-0.091138,0.150572,0.025292,-0.017407,-0.018527,0.063271,/home/face/prepared_baidu_faces_cp/sub_111/ï¿½ï¿½ï¿½...,/home/soyoung/face/baidu_full_pics_cp/sub_111/...,sub_111/ï¿½ï¿½ï¿½Â¤ï¿½ï¿½ï¿½ABP-308.jpg
21731,0.041103,0.063438,-0.028321,0.074898,-0.132749,0.058876,0.024055,-0.071332,-0.078203,-0.075727,...,-0.194742,0.049120,-0.037555,0.164845,0.056746,0.217023,0.120495,/home/face/prepared_baidu_faces_cp/sub_111/ï¿½ï¿½ï¿½...,/home/soyoung/face/baidu_full_pics_cp/sub_111/...,sub_111/ï¿½ï¿½ï¿½Åµï¿½ï¿½ï¿½Å·ï¿½ï¿½ï¿½ï¿½Õ¾ï¿½Ä°ï¿½07.jpg
21732,-0.004882,0.262674,-0.027674,0.116892,-0.025736,0.070203,0.011612,0.002691,0.025162,0.128748,...,0.061775,0.025029,0.082017,0.153350,-0.040926,0.100225,0.014192,/home/face/prepared_baidu_faces_cp/sub_111/ï¿½Ç²ï¿½...,/home/soyoung/face/baidu_full_pics_cp/sub_111/...,sub_111/ï¿½Ç²ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½.jpg

In [32]:
to_be_drop = df[df['name'].apply(lambda x: x in no)].index
to_be_drop

Int64Index([   60, 17132, 21728, 21731, 21732, 21742, 21744, 21747, 21748,
            21753,
            ...
            36053, 46410, 46533, 46560, 47273, 47476, 47481, 48366, 54837,
            55140],
           dtype='int64', length=169)

In [33]:
df.shape

(90711, 131)

In [34]:
df.drop(to_be_drop).shape

(90542, 131)

In [35]:
df_V2= df.drop(to_be_drop)
df_V2.shape

(90542, 131)

In [36]:
df_V3 = df_V2.reset_index(drop=True)
df_V3.shape

(90542, 131)

In [37]:
df_V3.tail()

,0,1,2,3,4,5,6,7,8,9,...,121,122,123,124,125,126,127,url,full_url,name
90537,0.003517,0.052479,-0.044540,0.089930,-0.028029,0.054476,0.062636,0.098270,0.111579,0.009150,...,0.021647,-0.102794,0.188510,-0.030728,-0.013842,-0.047551,0.039203,/home/face/prepared_baidu_faces_cp/sub_17/1397...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/13977132_597663.jpg
90538,0.030297,0.122150,-0.020289,0.030955,-0.067142,0.080773,0.100250,0.113896,-0.048586,0.022922,...,-0.029517,-0.004100,0.079527,0.006152,-0.015773,-0.028892,0.031459,/home/face/prepared_baidu_faces_cp/sub_17/1379...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/13799170921005952220031f9e06.jpg
90539,0.108930,-0.036421,-0.151056,0.065437,0.151416,-0.022955,0.069124,-0.000841,-0.000843,0.038638,...,0.119045,-0.076127,0.176795,-0.043373,-0.035653,-0.147453,-0.066531,/home/face/prepared_baidu_faces_cp/sub_17/1377...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/137795874348208_0.jpg
90540,0.076546,0.111801,-0.102897,0.136395,0.015714,0.078710,0.012302,0.009330,0.018362,0.073968,...,0.040410,-0.044080,0.179863,0.141644,-0.070568,0.029913,0.046886,/home/face/prepared_baidu_faces_cp/sub_17/1388...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/1388629689373.jpg
90541,0.095205,0.065115,-0.086386,0.142298,0.062028,0.032015,0.062714,0.025182,0.039111,0.017706,...,0.063335,-0.122442,0.203849,0.049614,-0.047644,-0.030951,0.004675,/home/face/prepared_baidu_faces_cp/sub_17/1388...,/home/soyoung/face/baidu_full_pics_cp/sub_17/1...,sub_17/1388471374472.jpg

In [38]:
df_V4 = df_V3.drop(['url'], axis=1)
df_V4 = df_V4.drop(['full_url'], axis=1)
df_V4.shape

(90542, 129)

In [39]:
df_V4.to_csv('new_batch_2.csv', index=False)

In [40]:
!pwd

/home/soyoung/face/baidu_face_project/96_data/batch1Data