In [1]:
import pandas as pd
import json
import collections
import numpy as np
from collections import OrderedDict

pd.options.display.max_columns=100
pd.options.display.max_colwidth=100
pd.options.display.max_rows=100

def flatten(d, parent_key='', sep='_'):
    items = []
    for k, v in d.items():
        new_key = parent_key + sep + k if parent_key else k
        if isinstance(v, collections.MutableMapping):
            items.extend(flatten(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return OrderedDict(items)

In [2]:
!dir

 Volume in drive C is OS
 Volume Serial Number is 9460-E68D

 Directory of C:\Users\riji\Desktop\vali\csv_valid

06/08/2017  04:39 PM    <DIR>          .
06/08/2017  04:39 PM    <DIR>          ..
06/08/2017  04:39 PM    <DIR>          .ipynb_checkpoints
06/08/2017  02:00 PM             2,659 annuity_finance.csv
06/08/2017  11:22 AM             5,757 annuity_loan.csv
06/08/2017  11:22 AM            35,131 annuity_master.csv
06/08/2017  02:00 PM            13,176 oas_fi_1_json.csv
06/08/2017  12:33 PM             1,359 policy_finance.csv
06/08/2017  11:22 AM             1,067 policy_loan.csv
06/08/2017  11:22 AM             1,014 policy_master.csv
06/08/2017  01:46 PM             9,466 Untitled-Copy1.ipynb
06/08/2017  12:39 PM             9,466 Untitled.ipynb
06/08/2017  12:56 PM            38,817 validation-Copy1.ipynb
06/08/2017  12:51 PM            89,671 validation-Copy2.ipynb
06/08/2017  01:09 PM            91,833 validation-Copy3.ipynb
06/08/2017  01:47 PM            91,833 validation-Copy4.ipynb
06/08/2017  01:52 PM           196,936 validation-Copy5.ipynb
06/08/2017  04:39 PM           132,170 validation-Copy6.ipynb
06/08/2017  03:28 PM            84,657 validation-loan-Copy1.ipynb
06/08/2017  04:38 PM           162,992 validation-loan.ipynb
06/08/2017  04:38 PM            37,141 validation-master-Copy1.ipynb
06/08/2017  04:38 PM            37,141 validation-master.ipynb
06/08/2017  01:58 PM           132,170 validation.ipynb
06/08/2017  11:22 AM            17,518 wnl_lo_1_json.csv
06/08/2017  11:22 AM            98,163 wnl_ma_1_json.csv
              22 File(s)      1,290,137 bytes
               3 Dir(s)  205,890,547,712 bytes free

# json finance

In [4]:
jf=pd.read_csv('wnl_ma_1_json.csv')
print jf.shape
jf.head(3)

(10, 219)

,marreckey,marname,maraddress,marnarasgsw,marnarbilsw,marnarownsw,marconvertedcasesw,marvalueerrorsw,marnarpayorsw,mar1035indicator,marquartstmtsw,marcommpdsw,marcommextrasw,marfordanvprintswchoice,marirsbkupwthsw,marorphanchoice,marsyswdhold,marpartialwdlsw,marmailcodeloan,marmailcodestatement,marmailcodebillnotice,marriderindicator,marissueage,marmatage,marsettlementoptns,marsex,marmaritalstatus,marcommntproperty,marsocsec,marstatus,marproductcode,marpriorprodcode,marplan,marpriorplan,marreinitemchoice,margroup,marissuestate,marcitytaxcodechoice,marsterlingrwnlswchoice,marclass,marcalcmethod,marcomments,marpriorstatus,marreasonprefix,marreasoncode,marbillingmethod,marbillingmode,marpolicyyear,marlastaccounttype,marlastaccounttran,...,mardirectcoinsuredind,marsunloanrate,maragencyadr,maragencyerr,marmgaadr,marmgaerr,marsmgaadrerr,marspiatolerance,marpffixedcounter,marpfinterimcounter,marpfindexcounter,marlasteffpaydate,margmwvamt,margmwbstartdate,margmwbstatuscode,marpytdgmwbwdlbenefit,marglbstartdate,marglbstatuscode,marglbincomebase,marpytdglbwdlbenefit,marglbincreaseratesw,marglbmaxannwdl,marverusswitches,marpolicyrider,marprnenhance,marprnplus,marincomecreditbase,marttlprnglbfee,marttlintglbfee,marpytdprnglbfee,marpytdintglbfee,marcmtdprnglbfee,marcmtdintglbfee,marlookbacksw,marglbcode,marcytdprnglbfee,marcytdintglbfee,marttlprnrecapamt,marttlintrecapamt,marpytdprnrecapamt,marpytdintrecapamt,marcytdprnrecapamt,marcytdintrecapamt,marincomevalue,marrecaptureatdeath,mardeathbenevalue,margmwvmaxannvvalue,marminincbase,mardolind,filler635
0,"{""marreccompany"":{""marreccompany1"":""1"",""marreccompany2"":""1""},""marrecpolnumbchoice"":{""marrecpolnu...","{""marnamelast"":{""marnamelast1"":""PLUX"",""marnamelast2"":""QS""},""marnamefirst"":""LVGXR"",""marnamemi"":""L""}","{""maraddr1"":""30420 327BX QCS"",""maraddr2"":"""",""marname2"":"""",""maraddr3"":{""marcity"":""AITKIN"",""marsta...",N,N,N,N,P,NaN,N,N,N,N,"{""marfordanvprintsw"":""N"",""mariaanvprintsw"":null}",N,"{""marorphan"":""A"",""mariacategory"":null}",NaN,N,NaN,NaN,NaN,N,65,105.0,"{""marstlopt1"":""CL"",""marstlopt2"":""10""}",F,U,N,"{""martaxid"":""417-44-4854""}","{""marstatus1"":""T"",""marstatus2"":""3""}",90,NaN,"{""marplan13choice"":{""marplan13"":{""marplanyear"":""9"",""marplantype"":""9A""},""marplan13x"":null},""marpl...",NaN,"{""marreinitem"":""0000"",""marreinitemnum"":null}","{""margroup1"":"""",""margroup2"":""""}",MN,"{""marcitytaxcode"":"""",""filler89"":null}","{""marsterlingrwnlsw"":"""",""marendowlttrsw"":null}",R,L,"{""marcomments1"":""AGE"",""marcomments2"":"""",""marcomments3"":{""marcomments3mm"":70,""marcomments3dd"":1,""...",I2,NaN,29,0,0,"{""marpolyy"":12}",2,TRM,...,NaN,0.0,NaN,NaN,NaN,NaN,"[{""marsmgaadr"":"""",""marsmgaerr"":""""},{""marsmgaadr"":"""",""marsmgaerr"":""""},{""marsmgaadr"":"""",""marsmgaer...",0.0,0,0,0,"{""marlefyear"":0,""marlefmm"":0,""marlefdd"":0}",0.0,"{""margmwbstartyear"":0,""margmwbstartmm"":0,""margmwbstartdd"":0}",N,0.0,"{""marglbstartyear"":0,""marglbstartmm"":0,""marglbstartdd"":0}",N,0.0,0.0,NaN,0.0,"{""marverusreasoncode"":0,""marverusfileerror"":"""",""marverusstatus"":{""marverusstatus1"":"""",""marveruss...","{""maraccdeathrider"":""U"",""mardalylivingrider"":""U"",""marincpayadvancerider"":""U"",""marextendedcarerid...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,"{""marreccompany"":{""marreccompany1"":""1"",""marreccompany2"":""1""},""marrecpolnumbchoice"":{""marrecpolnu...","{""marnamelast"":{""marnamelast1"":""YCXA"",""marnamelast2"":""OI""},""marnamefirst"":""JZBSB"",""marnamemi"":""""}","{""maraddr1"":""25651 MHLREW YCI"",""maraddr2"":"""",""marname2"":"""",""maraddr3"":{""marcity"":""APPLE VALLEY"",...",N,N,N,N,D,NaN,N,N,N,N,"{""marfordanvprintsw"":""A"",""mariaanvprintsw"":null}",N,"{""marorphan"":""A"",""mariacategory"":null}",NaN,Y,NaN,NaN,NaN,N,84,95.0,"{""marstlopt1"":""CL"",""marstlopt2"":""10""}",F,U,N,"{""martaxid"":""640-66-3242""}","{""marstatus1"":""T"",""marstatus2"":""2""}",90,NaN,"{""marplan13choice"":{""marplan13"":{""marplanyear"":""1"",""marplantype"":""2A""},""marplan13x"":null},""marpl...",NaN,"{""marreinitem"":""0000"",""marreinitemnum"":null}","{""margroup1"":"""",""margroup2"":""""}",MN,"{""marcitytaxcode"":"""",""filler89"":null}","{""marsterlingrwnlsw"":"""",""marendowlttrsw"":null}",N,L,"{""marcomments1"":""DOD"",""marcomments2"":"""",""marcomments3"":{""marcomments3mm"":11,""marcomments3dd"":15,...",I2,NaN,14,0,0,"{""marpolyy"":11}",2,TRM,...,NaN,0.0,NaN,NaN,NaN,NaN,"[{""marsmgaadr"":"""",""marsmgaerr"":""""},{""marsmgaadr"":"""",""marsmgaerr"":""""},{""marsmgaadr"":"""",""marsmgaer...",0.0,0,0,0,"{""marlefyear"":0,""marlefmm"":0,""marlefdd"":0}",0.0,"{""margmwbstartyear"":0,""margmwbstartmm"":0,""margmwbstartdd"":0}",N,0.0,"{""marglbstartyear"":0,""marglbstartmm"":0,""marglbstartdd"":0}",N,0.0,0.0,NaN,0.0,"{""marverusreasoncode"":14,""marverusfileerror"":""D"",""marverusstatus"":{""marverusstatus1"":""T"",""marver...","{""maraccdeathrider"":""U"",""mardalylivingrider"":""U"",""marincpayadvancerider"":""U"",""marextendedcarerid...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,"{""marreccompany"":{""marreccompany1"":""1"",""marreccompany2"":""1""},""marrecpolnumbchoice"":{""marrecpolnu...","{""marnamelast"":{""marnamelast1"":""ZPXS"",""marnamelast2"":""MTQY""},""marnamefirst"":""JAVF"",""marnamemi"":""I""}","{""maraddr1"":""0865 UDXDYJWWD FM IAS 926"",""maraddr2"":"""",""marname2"":"""",""maraddr3"":{""marcity"":""EDINA...",N,N,N,N,D,NaN,N,N,N,N,"{""marfordanvprintsw"":""A"",""mariaanvprintsw"":null}",N,"{""marorphan"":""A"",""mariacategory"":null}",NaN,Y,NaN,NaN,NaN,N,79,90.0,"{""marstlopt1"":""CL"",""marstlopt2"":""10""}",F,U,N,"{""martaxid"":""480-05-5192""}","{""marstatus1"":""T"",""marstatus2"":""2""}",90,NaN,"{""marplan13choice"":{""marplan13"":{""marplanyear"":""1"",""marplantype"":""2A""},""marplan13x"":null},""marpl...",NaN,"{""marreinitem"":""0000"",""marreinitemnum"":null}","{""margroup1"":"""",""margroup2"":""""}",MN,"{""marcitytaxcode"":"""",""filler89"":null}","{""marsterlingrwnlsw"":"""",""marendowlttrsw"":null}",N,L,"{""marcomments1"":""DOD"",""marcomments2"":"""",""marcomments3"":{""marcomments3mm"":6,""marcomments3dd"":21,""...",I2,NaN,12,0,0,"{""marpolyy"":11}",2,TRM,...,NaN,0.0,NaN,NaN,NaN,NaN,"[{""marsmgaadr"":"""",""marsmgaerr"":""""},{""marsmgaadr"":"""",""marsmgaerr"":""""},{""marsmgaadr"":"""",""marsmgaer...",0.0,0,0,0,"{""marlefyear"":0,""marlefmm"":0,""marlefdd"":0}",0.0,"{""margmwbstartyear"":0,""margmwbstartmm"":0,""margmwbstartdd"":0}",N,0.0,"{""marglbstartyear"":0,""marglbstartmm"":0,""marglbstartdd"":0}",N,0.0,0.0,NaN,0.0,"{""marverusreasoncode"":12,""marverusfileerror"":""D"",""marverusstatus"":{""marverusstatus1"":""T"",""marver...","{""maraccdeathrider"":""U"",""mardalylivingrider"":""U"",""marincpayadvancerider"":""U"",""marextendedcarerid...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

# unpack json manully ...

In [94]:
def one_row(jfc):
    save = OrderedDict()
    for i in jfc: 
        for j in jfc[i]:
            
#             if type(j)==type(''):
#                 if j[0]=='[' and j[-1]==']':
#                     j={}
            
            
            try:
                content =  flatten(json.loads(j, object_pairs_hook=OrderedDict)).items()
                for k in content:
                    
                    
                    save[k[0]]=k[1]
                    
            except:
                if type(j)==type(''):
                    if j[0]=='[' and j[-1]==']': 
#                         print j
                        x=json.loads(j, object_pairs_hook=OrderedDict)
                        print x
#                         for p in x:
#                             print p
#                             q = flatten(p)
                            
#                             print q

            
                
                save[i]=j

#     df = pd.DataFrame(save,index=[1])
#     return df

In [95]:
one_row(jfc)

[OrderedDict([(u'marsmgaanncode', u'NC')]), OrderedDict([(u'marsmgaanncode', u'NC')]), OrderedDict([(u'marsmgaanncode', u'NC')])]
[OrderedDict([(u'maragency', OrderedDict([(u'maragency0', u'0'), (u'maragency1', u'AP68')])), (u'maragencyregion', u'878'), (u'maragencysplit', 100.0), (u'maragentcodes', [OrderedDict([(u'marsubagent', u'006P1'), (u'maragentsplit', 100.0)]), OrderedDict([(u'marsubagent', u''), (u'maragentsplit', 0.0)])])]), OrderedDict([(u'maragency', OrderedDict([(u'maragency0', u''), (u'maragency1', u'')])), (u'maragencyregion', u''), (u'maragencysplit', 0.0), (u'maragentcodes', [OrderedDict([(u'marsubagent', u'00000000000'), (u'maragentsplit', 0.0)]), OrderedDict([(u'marsubagent', u''), (u'maragentsplit', 0.0)])])])]
[OrderedDict([(u'marsmga', OrderedDict([(u'marsmga0', u'0'), (u'marsmga1', u'0000000000')])), (u'marsmgacommcode', u'NC'), (u'marsmgarollcode', u'NC')]), OrderedDict([(u'marsmga', OrderedDict([(u'marsmga0', u'0'), (u'marsmga1', u'0000000000')])), (u'marsmgacommcode', u'NC'), (u'marsmgarollcode', u'NC')]), OrderedDict([(u'marsmga', OrderedDict([(u'marsmga0', u'0'), (u'marsmga1', u'0000000000')])), (u'marsmgacommcode', u'NC'), (u'marsmgarollcode', u'NC')])]
[OrderedDict([(u'marsmgairocode', u'NC'), (u'marsmgaabccode', u'NC')]), OrderedDict([(u'marsmgairocode', u'NC'), (u'marsmgaabccode', u'NC')]), OrderedDict([(u'marsmgairocode', u'NC'), (u'marsmgaabccode', u'NC')]), OrderedDict([(u'marsmgairocode', u''), (u'marsmgaabccode', u'')])]
[OrderedDict([(u'marsmgaada', u''), (u'marsmgaera', u'')]), OrderedDict([(u'marsmgaada', u''), (u'marsmgaera', u'')]), OrderedDict([(u'marsmgaada', u''), (u'marsmgaera', u'')]), OrderedDict([(u'marsmgaada', u''), (u'marsmgaera', u'')])]
[OrderedDict([(u'marsmgaadr', u''), (u'marsmgaerr', u'')]), OrderedDict([(u'marsmgaadr', u''), (u'marsmgaerr', u'')]), OrderedDict([(u'marsmgaadr', u''), (u'marsmgaerr', u'')]), OrderedDict([(u'marsmgaadr', u''), (u'marsmgaerr', u'')])]

In [84]:
x = json.loads("""[{"maragency":{"maragency0":"0","maragency1":"AP68"},"maragencyregion":"878","maragencysplit":100.0,"maragentcodes":[{"marsubagent":"006P1","maragentsplit":100.0},{"marsubagent":"","maragentsplit":0.0}]},{"maragency":{"maragency0":"","maragency1":""},"maragencyregion":"","maragencysplit":0.0,"maragentcodes":[{"marsubagent":"00000000000","maragentsplit":0.0},{"marsubagent":"","maragentsplit":0.0}]}]"""
          ,object_pairs_hook=OrderedDict)
x

[OrderedDict([(u'maragency',
               OrderedDict([(u'maragency0', u'0'), (u'maragency1', u'AP68')])),
              (u'maragencyregion', u'878'),
              (u'maragencysplit', 100.0),
              (u'maragentcodes',
               [OrderedDict([(u'marsubagent', u'006P1'),
                             (u'maragentsplit', 100.0)]),
                OrderedDict([(u'marsubagent', u''),
                             (u'maragentsplit', 0.0)])])]),
 OrderedDict([(u'maragency',
               OrderedDict([(u'maragency0', u''), (u'maragency1', u'')])),
              (u'maragencyregion', u''),
              (u'maragencysplit', 0.0),
              (u'maragentcodes',
               [OrderedDict([(u'marsubagent', u'00000000000'),
                             (u'maragentsplit', 0.0)]),
                OrderedDict([(u'marsubagent', u''),
                             (u'maragentsplit', 0.0)])])])]

In [81]:
type(x)

list

In [82]:
for i in x:
    print i

OrderedDict([(u'maragency', OrderedDict([(u'maragency0', u'0'), (u'maragency1', u'AP68')])), (u'maragencyregion', u'878'), (u'maragencysplit', 100.0), (u'maragentcodes', [OrderedDict([(u'marsubagent', u'006P1'), (u'maragentsplit', 100.0)]), OrderedDict([(u'marsubagent', u''), (u'maragentsplit', 0.0)])])])
OrderedDict([(u'maragency', OrderedDict([(u'maragency0', u''), (u'maragency1', u'')])), (u'maragencyregion', u''), (u'maragencysplit', 0.0), (u'maragentcodes', [OrderedDict([(u'marsubagent', u'00000000000'), (u'maragentsplit', 0.0)]), OrderedDict([(u'marsubagent', u''), (u'maragentsplit', 0.0)])])])

In [77]:
one_row(jfc)

[{"marsmgaanncode":"NC"},{"marsmgaanncode":"NC"},{"marsmgaanncode":"NC"}]
[{"maragency":{"maragency0":"0","maragency1":"AP68"},"maragencyregion":"878","maragencysplit":100.0,"maragentcodes":[{"marsubagent":"006P1","maragentsplit":100.0},{"marsubagent":"","maragentsplit":0.0}]},{"maragency":{"maragency0":"","maragency1":""},"maragencyregion":"","maragencysplit":0.0,"maragentcodes":[{"marsubagent":"00000000000","maragentsplit":0.0},{"marsubagent":"","maragentsplit":0.0}]}]
[{"marsmga":{"marsmga0":"0","marsmga1":"0000000000"},"marsmgacommcode":"NC","marsmgarollcode":"NC"},{"marsmga":{"marsmga0":"0","marsmga1":"0000000000"},"marsmgacommcode":"NC","marsmgarollcode":"NC"},{"marsmga":{"marsmga0":"0","marsmga1":"0000000000"},"marsmgacommcode":"NC","marsmgarollcode":"NC"}]
[{"marsmgairocode":"NC","marsmgaabccode":"NC"},{"marsmgairocode":"NC","marsmgaabccode":"NC"},{"marsmgairocode":"NC","marsmgaabccode":"NC"},{"marsmgairocode":"","marsmgaabccode":""}]
[{"marsmgaada":"","marsmgaera":""},{"marsmgaada":"","marsmgaera":""},{"marsmgaada":"","marsmgaera":""},{"marsmgaada":"","marsmgaera":""}]
[{"marsmgaadr":"","marsmgaerr":""},{"marsmgaadr":"","marsmgaerr":""},{"marsmgaadr":"","marsmgaerr":""},{"marsmgaadr":"","marsmgaerr":""}]

In [48]:
def all_row(jf):
    
    for i in np.arange(jf.shape[0]):
        ret = jf.iloc[i:i+1,:]
        if i == 0:
            df = one_row(ret)
        else:
            df = df.append(one_row(ret))
    return df.reset_index().drop('index',1)

In [9]:
df = all_row(jf)
df

ValueError: could not broadcast input array from shape (2) into shape (1)

# raw finance

In [13]:
rf = pd.read_csv('annuity_master.csv')
print rf.shape
rf.head(10)

(10, 538)

,mar_rec_company_1,mar_rec_company_2,mar_rec_pol_nbr1,mar_rec_pol_nbr2,mar_rec_pol_numb_1_2,mar_rec_pol_numb_3,mar_rec_pol_numb_rest,mar_rec_pol_numb_1_5,mar_rec_pol_numb_rest_e,mar_name_last_1,mar_name_last_2,mar_name_first,mar_name_mi,mar_addr_1,mar_addr_2,mar_name_2,mar_city,mar_state,mar_zip,mar_walk_numb,mar_tele_numb,mar_nar_asg_sw,mar_nar_bil_sw,mar_nar_own_sw,mar_converted_case_sw,mar_value_error_sw,mar_nar_payor_sw,mar_1035_indicator,mar_quart_stmt_sw,mar_comm_pd_sw,mar_comm_extra_sw,mar_ford_anv_print_sw,mar_ia_anv_print_sw,mar_irs_bkup_wth_sw,mar_orphan,mar_ia_category,mar_sys_wd_hold,mar_partial_wdl_sw,mar_mail_code_loan,mar_mail_code_statement,mar_mail_code_bill_notice,mar_rider_indicator,mar_issue_age,mar_mat_age,mar_stl_opt_1,mar_stl_opt_2,mar_sex,mar_marital_status,mar_commnt_property,mar_tax_id,...,mar_pytd_glb_wdl_benefit,mar_glb_increase_rate_sw,mar_glb_max_ann_wdl,mar_verus_reason_code,mar_verus_file_error,mar_verus_status_1,mar_verus_status_2,mar_acc_death_rider,mar_daly_living_rider,mar_inc_pay_advance_rider,mar_extended_care_rider,mar_glb_rider,mar_intrst_bailout_rider,mar_inc_st_date_adj_rider,mar_lifetime_inc_rider,mar_mva_rider,mar_terminal_ill_rider,mar_qlac,mar_waiver_of_assignmnt,mar_commutation_rider,mar_trail_comm_ind,mar_prn_enhance,mar_prn_plus,mar_income_credit_base,mar_ttl_prn_glb_fee,mar_ttl_int_glb_fee,mar_pytd_prn_glb_fee,mar_pytd_int_glb_fee,mar_cmtd_prn_glb_fee,mar_cmtd_int_glb_fee,mar_lookback_sw,mar_glb_code,mar_cytd_prn_glb_fee,mar_cytd_int_glb_fee,mar_ttl_prn_recap_amt,mar_ttl_int_recap_amt,mar_pytd_prn_recap_amt,mar_pytd_int_recap_amt,mar_cytd_prn_recap_amt,mar_cytd_int_recap_amt,mar_income_value,mar_recapture_at_death,mar_death_bene_value,mar_gmwv_max_annv_value,mar_min_inc_base,mar_dol_ind,mar_upfront_comm_ind,filler_7,prcss_cntrl_id,load_dt
0,S,1,2,CE12208,NaN,NaN,NaN,NaN,NaN,JF M,BKY,AJBRX,NaN,7813 Z 6UH NHN,NaN,NaN,BAY SHORE,NY,117063023,NaN,5361701603,N,N,Y,N,NaN,NaN,N,N,N,N,Y,NaN,N,A,NaN,NaN,N,NaN,NaN,NaN,N,65,105.0,CL,10,M,U,N,509-15-0098,...,0.0,NaN,0.0,0,NaN,NaN,NaN,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,z,NaN,3,2017-06-07
1,S,1,2,CE12209,NaN,NaN,NaN,NaN,NaN,HKNZ,AXAT WVLMHL,PPOYKG,NaN,5874 01YF ZJ,NaN,NaN,OZONE PARK,NY,114161307,NaN,4639519848,N,N,N,N,NaN,NaN,N,N,N,N,N,NaN,N,A,NaN,NaN,N,NaN,NaN,NaN,N,46,105.0,CL,10,F,U,N,973-09-4820,...,0.0,NaN,0.0,0,NaN,NaN,NaN,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23615.32,0.0,0.0,7.0,z,NaN,3,2017-06-07
2,S,1,2,CE12210,NaN,NaN,NaN,NaN,NaN,COOW,OI,QRVOAMN R,O,7147 21PA BNK QAN 1D,NaN,NaN,WOODSIDE,NY,113772905,0.0,7835467886,N,N,N,N,P,NaN,N,N,N,N,N,NaN,N,A,NaN,NaN,N,NaN,NaN,NaN,N,67,95.0,CL,10,F,U,N,701-01-5468,...,0.0,NaN,0.0,0,NaN,NaN,NaN,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,406267.04,0.0,0.0,7.0,z,NaN,3,2017-06-07
3,S,1,2,CE12211,NaN,NaN,NaN,NaN,NaN,MOCN,Y,TTRBJ,NaN,29 LLDSMIBIN PBG,NaN,NaN,GREENLAWN,NY,117403133,NaN,7091682242,N,N,N,N,D,NaN,N,N,N,N,Y,NaN,N,A,NaN,NaN,Y,NaN,NaN,NaN,N,85,105.0,CL,10,F,U,N,128-96-2475,...,0.0,NaN,0.0,12,D,T,2.0,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,z,NaN,3,2017-06-07
4,S,1,2,CE12212,NaN,NaN,NaN,NaN,NaN,ETXE,AOJMR,OZYLCRDJ,NaN,12833 393YC LTP,NaN,NaN,JAMAICA,NY,114362233,NaN,5794202841,N,N,N,N,NaN,NaN,N,N,N,N,N,NaN,N,A,NaN,NaN,N,NaN,NaN,NaN,N,63,105.0,CL,10,F,U,N,381-62-5681,...,0.0,NaN,0.0,0,NaN,NaN,NaN,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11660.42,0.0,0.0,7.0,z,NaN,3,2017-06-07
5,S,1,2,CE12213,NaN,NaN,NaN,NaN,NaN,UCOE,B,ENXIDM,NaN,457 B 41WO GV,NaN,NaN,BROOKLYN,NY,112033703,NaN,3924784485,N,N,N,N,NaN,NaN,N,N,N,N,N,NaN,N,A,NaN,NaN,N,NaN,NaN,NaN,N,57,105.0,CL,10,F,U,N,834-43-8304,...,0.0,NaN,0.0,0,NaN,NaN,NaN,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23320.86,0.0,0.0,7.0,z,NaN,3,2017-06-07
6,S,1,2,CE12214,NaN,NaN,NaN,NaN,NaN,KLZW,SPN,CCFRCMP,D,8068 BG LKQGSNN 0,NaN,NaN,PETERSBURG,NY,121386012,0.0,602142114,N,N,N,N,D,NaN,N,N,N,N,Y,NaN,N,A,NaN,NaN,Y,NaN,NaN,NaN,N,67,105.0,CL,10,M,U,N,090-17-5027,...,0.0,NaN,0.0,12,D,T,2.0,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,z,NaN,3,2017-06-07
7,S,1,2,CE12215,NaN,NaN,NaN,NaN,NaN,AWCA,L,OFGGULY,B,9693 DURPWVO FW DA 5,NaN,NaN,BROOKLYN,NY,112124525,0.0,9078903701,N,N,N,N,NaN,NaN,N,N,N,N,N,NaN,N,A,NaN,NaN,N,NaN,NaN,NaN,N,66,105.0,CL,10,M,U,N,983-65-7155,...,0.0,NaN,0.0,0,NaN,NaN,NaN,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11235.75,0.0,0.0,7.0,z,NaN,3,2017-06-07
8,S,1,2,CE12216,NaN,NaN,NaN,NaN,NaN,SAPA,YBI,QUAER,Y,134 MAUZVY QNH PCV 1N,NaN,NaN,BROOKLYN,NY,112132123,0.0,7050414526,N,N,N,N,NaN,NaN,N,N,N,N,Y,NaN,N,A,NaN,NaN,Y,NaN,NaN,NaN,N,61,105.0,CL,10,M,U,N,887-87-8643,...,0.0,NaN,0.0,0,NaN,NaN,NaN,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,NaN,z,NaN,3,2017-06-07
9,S,1,2,CE12217,NaN,NaN,NaN,NaN,NaN,XLOM,NSB,LUBPAWRB,NaN,1332 IAJNGFHJ OMR,NaN,NaN,BRONX,NY,104622100,NaN,2359887446,N,N,N,N,NaN,NaN,N,N,N,N,N,NaN,N,A,NaN,NaN,N,NaN,NaN,NaN,N,69,105.0,CL,10,M,U,N,508-79-9996,...,0.0,NaN,0.0,0,NaN,NaN,NaN,U,U,U,U,U,U,U,U,U,U,U,U,U,U,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7886.30,0.0,0.0,7.0,z,NaN,3,2017-06-07

# compare column data
# json VS. raw, finance, first 10 rows

# the values are diff, but assume the sequence of json and finance are diff
* will valid later by select * from table where condition (firm policy number), find a same record both in json and raw

### last 2 row in raw are added

In [187]:
compare = pd.concat([pd.DataFrame(df.columns, columns=['json']), 
                     pd.DataFrame(df.iloc[0].values, columns=['json_value']), 
                     pd.DataFrame(rf.iloc[0].values, columns=['raw_value']), 
                     pd.DataFrame(rf.columns, columns=['raw'])]
                     , axis=1)

compare

,json,json_value,raw_value,raw
0,firreccompany_firreccompany1,1,S,fir_rec_company_1
1,firreccompany_firreccompany2,1,1,fir_rec_company_2
2,firrecpolnumb,FD208731,2NY01962,fir_rec_pol_numb
3,firreccalcmethod,L,L,fir_rec_calc_method
4,firreceffdatechoice_firreceffdate,None,NaN,fir_rec_eff_date
5,firreceffdatechoice_filler9_firredyearchoice_firredyear,None,NaN,fir_red_year
6,firreceffdatechoice_filler9_firredyearchoice_filler11_firredcc,20,20,fir_red_cc
7,firreceffdatechoice_filler9_firredyearchoice_filler11_firredyy,1,5,fir_red_yy
8,firreceffdatechoice_filler9_firredmm,5,12,fir_red_mm
9,firreceffdatechoice_filler9_firreddd,29,22,fir_red_dd
10,firrecitem,239,635,fir_rec_item
11,firplancode,11HWN,26DVB,fir_plan_code
12,firconsolidationcode,C,C,fir_consolidation_code
13,firstatus1,T,I,fir_status1
14,firstatus2,R,1,fir_status2
15,firiedyearchoice_firiedyear,None,NaN,fir_ied_year
16,firiedyearchoice_filler24_firiedcc,20,20,fir_ied_cc
17,firiedyearchoice_filler24_firiedyy,12,17,fir_ied_yy
18,firiedmm,5,12,fir_ied_mm
19,firieddd,1,1,fir_ied_dd
20,firnavyearchoice_firnavyear,None,NaN,fir_nav_year
21,firnavyearchoice_filler31_firnavcc,20,20,fir_nav_cc
22,firnavyearchoice_filler31_firnavyy,12,17,fir_nav_yy
23,firnavmm,5,12,fir_nav_mm
24,firnavdd,29,22,fir_nav_dd
25,firnxtaccmval,0,6049.94,fir_nxt_accm_val
26,firttlprndeposit,30004.9,4000,fir_ttl_prn_deposit
27,firttlintdeposit,0,0,fir_ttl_int_deposit
28,firttlintearned,0,0,fir_ttl_int_earned
29,firttlprnwthdrwl,30004.9,0,fir_ttl_prn_wthdrwl
30,firttlprnsurrchrg,0,0,fir_ttl_prn_surr_chrg
31,firttlintsurrchrg,0,0,fir_ttl_int_surr_chrg
32,firttlintpaid,18714.8,0,fir_ttl_int_paid
33,firitemintrate,0.035,0.03,fir_item_int_rate
34,fircmtdbgnvalue,0,5935.41,fir_cmtd_bgn_value
35,fircmtddeposit,0,0,fir_cmtd_deposit
36,fircmtdwthdrwl,0,0,fir_cmtd_wthdrwl
37,fircmtdpriordeposit,0,0,fir_cmtd_prior_deposit
38,firlmdyearchoice_firlmdyear,None,NaN,fir_lmd_year
39,firlmdyearchoice_firlmdyearr_firlmdcc,20,20,fir_lmd_cc
40,firlmdyearchoice_firlmdyearr_firlmdyy,12,5,fir_lmd_yy
41,firlmdmm,3,12,fir_lmd_mm
42,firlmddd,23,27,fir_lmd_dd
43,firloanintrate,0,0,fir_loan_int_rate
44,firttlloanamt,0,0,fir_ttl_loan_amt
45,firttlloanintearn,0,0,fir_ttl_loan_int_earn
46,firttlloanamt2,0,0,fir_ttl_loan_amt_2
47,firttlloanintearn2,0,0,fir_ttl_loan_int_earn_2
48,firagabonus,0,0,fir_aga_bonus
49,firttlpremremaining,0,4000,fir_ttl_prem_remaining
50,firnegcostbasisreceived,0,0,fir_neg_cost_basis_received
51,firdarcode,None,NaN,fir_dar_code
52,firrenewaldur,0,0,fir_renewal_dur
53,firsuntranscode,NaN,NaN,fir_sun_trans_code
54,firlastrenewaldate,NaN,0,fir_last_renewal_date
55,firfirstyrpremamt,0,0,fir_first_yr_prem_amt
56,firbonuswithdrawal,0,0,fir_bonus_withdrawal
57,filler72,NaN,NaN,filler
58,NaN,NaN,2,prcss_cntrl_id
59,NaN,NaN,2017-06-07,load_dt