In [1]:
import pandas as pd
import os
from time import ctime
import matplotlib.pyplot as plt
import seaborn as sns
pd.options.display.max_rows=300

In [2]:
%%time
fl=pd.read_csv('./prepared_train_27Dec.csv', chunksize=10000, low_memory=False)
data = pd.concat([i for i in fl], ignore_index=True)
data['user_id'] = data['userId'].astype(int)
print data.shape

label = pd.read_csv('./Training_set.csv')
print label.shape

df = data.set_index('user_id').join(label.set_index('user_id'), how='inner', lsuffix='data_')
print df.shape

(195186, 93)
(108011, 3)
(102514, 94)
CPU times: user 5.99 s, sys: 687 ms, total: 6.68 s
Wall time: 6.67 s

In [5]:
df.head(1).transpose()

user_id                                                                                    1018449
indexdata_                                                                           techit99.html
about.avatar                                     /ppic/1869150/logo/1018449/profile_logo_101844...
about.avatar_cdn                                 //cdn2.f-cdn.com/ppic/1869150/logo/1018449/pro...
about.avatar_large                                /ppic/1869149/logo/1018449/profile-image-250.png
about.avatar_large_cdn                           //cdn3.f-cdn.com/ppic/1869149/logo/1018449/pro...
about.chosen_role                                                                                2
about.company                                                                                itsol
about.display_name                                                                        techit99
about.hourly_rate                                                                               60
about.id                                                                               1.01845e+06
about.primary_language                                                                          en
about.profile_description                                                                      NaN
about.public_name                                                                         techit99
about.recommendations                                                                            0
about.registration_date                                                                1.23793e+09
about.registration_date_human                                                          March, 2009
about.registration_date_localized                                                   March 24, 2009
about.responsivenessText                                                                       NaN
about.role                                                                                       1
about.tagline                                                                                  NaN
about.username                                                                            techit99
about.username_sentence                                                                   Techit99
hourlyRate                                                                                      60
resume.certifications                            [{u'award_date': u'2011', u'descr': u'Hootsuit...
resume.education                                                                                []
resume.exams                                                                                    []
resume.experience                                [{u'year_interval': u'-2011', u'month_interval...
resume.publications                                                                             []
resume.show                                                                                   True
skills                                           [{u'usages': 0, u'seo_url': u'php', u'islocal'...
timeOffset                                                                                       0
userId                                                                                 1.01845e+06
username                                                                                  techit99
public_firstname                                                                          techit99
current_image.url                                //cdn2.f-cdn.com/static/img/profiles/cover-pro...
city                                                                                       Bristol
country.code                                                                                    gb
country.flag_class                                                                  united-kingdom
country.flag_url                                                             /img/flags/png/gb.png
country.flag_url_cdn                                         //cdn6.f-cdn.com/img/flags/png/gb.png
country.highres_flag_url                                 /img/flags/highres_png/united-kingdom.png
country.highres_flag_url_cdn                     //cdn5.f-cdn.com/img/flags/highres_png/united-...
country.name                                                                        United Kingdom
code                                                                                           USD
country                                                                                         US
exchange_rate                                                                                    1
id                                                                                               1
name                                                                                     US Dollar
sign                                                                                             $
earnings_score                                                                                   0
entire_history.all                                                                               0
entire_history.category_ratings.communication                                                    0
entire_history.category_ratings.expertise                                                        0
entire_history.category_ratings.hire_again                                                       0
entire_history.category_ratings.professionalism                                                  0
entire_history.category_ratings.quality                                                          0
entire_history.complete                                                                          0
entire_history.completion_rate                                                                   0
entire_history.incomplete                                                                        0
entire_history.incomplete_reviews                                                                0
entire_history.on_budget                                                                         0
entire_history.on_time                                                                           0
entire_history.overall                                                                           0
entire_history.positive                                                                          0
entire_history.rehire_rate                                                                       0
entire_history.reviews                                                                           0
job_history.count_other                                                                          0
job_history.job_counts                                                                          []
summary.completion_rate                                                                        NaN
summary.earnings_score                                                                           0
summary.earnings_score_pc                                                                        0
summary.on_budget                                                                              NaN
summary.on_time                                                                                NaN
summary.rating_score                                                                             0
summary.rehire_rate                                                                            NaN
summary.reviews                                                                                  0
deposit_made                                                                                  True
facebook_connected                                                                           False
payment_verified                                                                             False
phone_verified                                                                               False
profile_complete                                                                              True
country.1                                                                                       UK
id.1                                                                                           262
offset                                                                                           1
timezone                                                                             Europe/London
job_history.job_counts_LEN                                                                       0
resume.certifications_LEN                                                                        1
resume.education_LEN                                                                             0
resume.exams_LEN                                                                                 0
resume.experience_LEN                                                                            1
resume.publications_LEN                                                                          0
skills_LEN                                                                                      15
index                                                                                        46287
label                                                                                            1

In [19]:
from time import time

In [20]:
time()

1514426280.826392

In [12]:
a=set([3])

In [15]:
a.add(4)
a

{3, 4}

In [23]:
df.to_csv('train.label.golden.csv')