In [17]:
import pandas as pd
pd.options.display.max_columns=100
pd.options.display.max_rows=1000

In [2]:
df=pd.read_csv('UCONN Updated 10 Years.csv')
df.shape

/home/saya/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (17,18,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(1558719, 24)

In [11]:
df[df['state'].isnull()].shape

(313776, 24)

In [13]:
one = df[~df['state'].isnull()]

In [14]:
one.shape

(1244943, 24)

In [33]:
one['state'] = one['state'].apply(lambda x: str(x).upper().strip().replace(',','').replace('.',''))

/home/saya/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [29]:
one.shape

(1244943, 24)

In [36]:
# one['state'].value_counts()

In [34]:
(one['state'].value_counts()>400).sum()

59

In [43]:
one['state'].value_counts().count()

252

In [68]:
save = list(one['state'].value_counts()[one['state'].value_counts()>400].index)

In [72]:
two = one[one['state'].apply(lambda x: str(x) in save)]
two.shape

(1243807, 24)

In [74]:
two.to_csv('clean_state.csv', index=False)

In [3]:
# df.iloc[12168,:]

In [8]:
zp=pd.read_csv('zip_code.csv')
zp.shape

/home/saya/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1,2,23,24,25,27,29,39,40,41,42,43,44,45,46,47,48,49,50,51,52,54,57,58,59,61) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(941296, 62)

In [10]:
df['state'].value_counts(dropna=False).head(10)

NaN    313776
MI      78811
NY      66802
CT      56152
NC      54045
NJ      48955
PA      47672
ON      45759
OH      44552
WI      42608
Name: state, dtype: int64

In [11]:
df['price'].value_counts().head(10)

0.0      620622
120.0    182957
100.0    182203
60.0     129000
90.0     115583
75.0      90083
70.0      57059
50.0      48082
150.0     32662
35.0      23629
Name: price, dtype: int64

In [20]:
df['job_sold'].sum()

24479.0

In [12]:
df[df['job_sold']==1][:5]

,id,name,address,city,state,zip,type,source,association,service_type,received_time,sent_time,company,status,price,campaign,is_mobile,landing_page,contact_page,previous_page,inbound_number,call_status,duration,job_sold
4,1003614,monica,1611 east elmer rd,east vineland,NJ,NaN,Supercharged Phone Leads,PPC Campaign (clicked on a PPC ad),"Basement Systems, Inc.",Basement Waterproofing,2007-08-01 09:31:39,2007-08-01 09:31:39,Dry Guys Basement Systems,Billable Lead,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
126,1003858,Ronald,142 S. 42nd Street,Bellingham,WA,98229,Supercharged Web Leads,Organic Search,"Basement Systems, Inc.",Basement Waterproofing,2007-08-07 21:44:51,2007-08-07 21:44:51,Rainy Day Basement Systems,Billable Lead,120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
132,1003869,arthur,12 anthony rd,north redding,MA,01864,Supercharged Phone Leads,Organic Search,"Basement Systems, Inc.",Basement Waterproofing,2007-08-08 09:12:21,2007-08-08 09:12:21,Northeast Basement Systems,Billable Lead,60.0,Phone Transfer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
157,1003901,Pamela,897 S. Spring Rd,Vineland,NJ,08361,Supercharged Web Leads,Organic Search,"Basement Systems, Inc.",Basement Waterproofing,2007-08-09 07:45:16,2007-08-09 07:45:16,Dry Guys Basement Systems,Billable Lead,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
228,1004033,Ron,10219 133rd PL SE,Snohomish,WA,98296,Supercharged Web Leads,Organic Search,"Basement Systems, Inc.",Basement Waterproofing,2007-08-13 17:56:27,2007-08-13 17:56:27,Rainy Day Basement Systems,Billable Lead,120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [13]:
# df['duration']

In [14]:
df.tail(5)

,id,name,address,city,state,zip,type,source,association,service_type,received_time,sent_time,company,status,price,campaign,is_mobile,landing_page,contact_page,previous_page,inbound_number,call_status,duration,job_sold
1558714,10364328,no name provided,NaN,Toronto,OH,43964,Supercharged Phone Leads,Organic Search,"Basement Systems, Inc.",Basement Waterproofing,2017-08-09 14:32:33,2017-08-30 14:52:11,Superior Basement Systems,Billable Lead,60.0,NaN,NaN,http://www.superiorbasementsystems.com/service...,NaN,NaN,8.553632e+09,ANSWER,246.0,NaN
1558715,10364331,Gus,NaN,Livingston,NJ,07039,Supercharged Phone Leads,PPC Campaign (clicked on a PPC ad),Relia-Serve,Concrete,2017-08-29 15:08:24,2017-08-30 14:52:34,Quality Concrete,Billable Lead,25.0,iPhone,1.0,NaN,NaN,NaN,8.886794e+09,ANSWER,241.0,NaN
1558716,10364337,Walter,248 20th Street Southwest,Birmingham,AL,35211,Supercharged Phone Leads,Organic Search,"Dr. Energy Saver, Inc.",HVAC Service - New Customer,2017-08-09 14:55:41,2017-08-30 14:53:13,Standard Heating & Air Conditioning Company,Billable Lead,60.0,Voicestar,NaN,NaN,NaN,NaN,2.052241e+09,ANSWER,295.0,NaN
1558717,10364340,No Name,NaN,NaN,NaN,NaN,Supercharged Phone Leads,PPC Campaign (clicked on a PPC ad),"Basement Systems, Inc.",Basement Waterproofing,2017-08-29 15:44:28,2017-08-30 14:53:49,Nova Basement Systems,Billable Lead,60.0,iPhone,1.0,NaN,NaN,NaN,8.774938e+09,ANSWER,175.0,NaN
1558718,10364343,Jim,3137 Leftwich St NW,Huntsville,AL,35810,Supercharged Phone Leads,Organic Search,CleanSpace,Crawl Space,2017-08-09 14:35:37,2017-08-30 14:54:22,AFS Foundation & Waterproofing Specialists,Billable Lead,90.0,Voicestar,NaN,NaN,NaN,NaN,2.564185e+09,ANSWER,352.0,NaN

In [15]:
df.columns

Index([u'id', u'name', u'address', u'city', u'state', u'zip', u'type',
       u'source', u'association', u'service_type', u'received_time',
       u'sent_time', u'company', u'status', u'price', u'campaign',
       u'is_mobile', u'landing_page', u'contact_page', u'previous_page',
       u'inbound_number', u'call_status', u'duration', u'job_sold'],
      dtype='object')

In [22]:
df.shape

(1558719, 24)

In [21]:
for i in df:
    print i
    print df[i].value_counts(dropna=False).head(7)
    print

id
8390655    1
8172227    1
8325812    1
9301047    1
8329910    1
8350392    1
8340157    1
Name: id, dtype: int64

name
NaN        155840
John        22565
David       18029
Michael     14393
Mike        14355
No Name     12366
Chris       12020
Name: name, dtype: int64

address
NaN                             365363
iPhone/Mobile Lead                 397
no address given                   223
None given                         135
30401 Agoura Road, Suite 200       103
1225 Wilshire Boulevard             64
Wet N Wild Way                      53
Name: address, dtype: int64

city
NaN             308714
Portland         10806
Birmingham        9242
Omaha             8940
Indianapolis      8585
Denver            7167
Saint Louis       6941
Name: city, dtype: int64

state
NaN    313776
MI      78811
NY      66802
CT      56152
NC      54045
NJ      48955
PA      47672
Name: state, dtype: int64

zip
NaN      354889
46032      1327
14850      1271
06824      1256
63376      1232
35242      1226
06880      1214
Name: zip, dtype: int64

type
Supercharged Phone Leads    875615
Supercharged Web Leads      683104
Name: type, dtype: int64

source
Organic Search                                                       467570
PPC Campaign (clicked on a PPC ad)                                   438546
Blended Search Traffic (from Google, with no keyword data)           313553
Other Campaign (site ads, affiliate programs, etc.)                  137127
Own Site (customer typed your domain name into their address bar)     95858
Unknown                                                               29670
Direct Search Traffic (customer searched for your brand)              20552
Name: source, dtype: int64

association
Basement Systems, Inc.           575334
Foundation Supportworks, Inc.    226449
Dr. Energy Saver, Inc.           146296
My Lead Tracking                 142376
CleanSpace                       138559
CN - Roofing Nation               94515
PolyLevel                         77815
Name: association, dtype: int64

service_type
Basement Waterproofing    490806
Foundation Repair         215783
NaN                       149362
Crawl Space               148057
PolyLEVEL                  81081
Insulation                 48174
Roof Repair                42991
Name: service_type, dtype: int64

received_time
2011-01-10 14:16:35    7
2016-02-17 14:18:53    6
2010-08-05 09:08:52    4
2016-04-19 11:40:28    4
2017-02-22 13:55:11    4
2016-02-17 14:18:52    4
2011-03-22 11:03:32    4
Name: received_time, dtype: int64

sent_time
0000-00-00 00:00:00    51
2014-03-04 17:35:57    23
2015-02-18 12:22:18    20
2015-02-18 12:22:33    19
2015-02-18 12:22:19    19
2015-02-18 12:22:16    19
2015-02-18 12:22:20    19
Name: sent_time, dtype: int64

company
Connecticut Basement Systems                  74906
Foundation Systems of Michigan                49888
AFS Foundation & Waterproofing Specialists    45003
Thrasher                                      39201
Woods Basement Systems                        31462
AquaGuard Foundation Solutions                30272
Badger Basement Systems                       29714
Name: company, dtype: int64

status
Billable Lead    1080074
No Charge         478645
Name: status, dtype: int64

price
0.0      620622
120.0    182957
100.0    182203
60.0     129000
90.0     115583
75.0      90083
70.0      57059
Name: price, dtype: int64

campaign
NaN                   1158422
Voicestar              254942
PPC Voicestar           70973
iPhone                  68490
Phone Transfer           3396
PPC Phone Transfer       1345
Web Lead                  287
Name: campaign, dtype: int64

is_mobile
NaN     1250545
 1.0     265937
 0.0      42237
Name: is_mobile, dtype: int64

landing_page
NaN                                           732214
http://www.drymich.com/                         9571
http://www.woodsbasementsystems.com/            5044
http://www.connecticutbasementsystems.com/      4820
http://www.alabamafoundationrepair.com/         4672
http://www.aquaguard.net/                       4200
http://www.badgerbasementsystems.com/           4065
Name: landing_page, dtype: int64

contact_page
NaN                                                                          926969
http://www.drymich.com/free-inspection/confirmation.html                      23552
http://www.woodsbasementsystems.com/free-estimate/confirmation.html           11810
http://www.connecticutbasementsystems.com/free-estimate/confirmation.html     10999
http://www.badgerbasementsystems.com/free-estimate/confirmation.html          10759
http://www.aquaguard.net/free-estimate/confirmation.html                       8998
http://www.innovativebasementsystems.com/free-estimate/confirmation.html       8768
Name: contact_page, dtype: int64

previous_page
NaN                                                             967089
http://www.drymich.com/free-inspection.html                      16679
http://www.connecticutbasementsystems.com/free-estimate.html      8805
http://www.badgerbasementsystems.com/free-estimate.html           8769
http://www.aquaguard.net/free-estimate.html                       8026
http://www.woodsbasementsystems.com/free-estimate.html            7455
http://www.midwestbasementsystems.com/free-estimate.html          6997
Name: previous_page, dtype: int64

inbound_number
NaN              708748
 0.000000e+00     27618
 8.884926e+09      5206
 8.007681e+09      5165
 7.342062e+09      4647
 2.564185e+09      3836
 8.886693e+09      3536
Name: inbound_number, dtype: int64

call_status
ANSWER        844697
NaN           708748
CANCEL          3468
NOANSWER         679
completed        527
VOICEMAIL        506
NOFORWARDS        49
Name: call_status, dtype: int64

duration
NaN      708748
 90.0      2241
 93.0      2211
 87.0      2207
 92.0      2202
 88.0      2192
 85.0      2182
Name: duration, dtype: int64

job_sold
NaN     1534240
 1.0      24479
Name: job_sold, dtype: int64

In [8]:
zp.head()

,zipcode.id,zipcode.zip,zipcode.fsa,zipcode.primary_record,zipcode.population,zipcode.households_per_zipcode,zipcode.white_population,zipcode.black_population,zipcode.hispanic.population,zipcode.asian_population,zipcode.hawaiian_population,zipcode.indian_population,zipcode.other_population,zipcode.male_population,zipcode.female_population,zipcode.persons_per_household,zipcode.avarage_house_value,zipcode.income_per_household,zipcode.latitude,zipcode.longitude,zipcode.elevation,zipcode.state,zipcode.state_full_name,zipcode.city_type,zipcode.city_alias_abbreviation,zipcode.area_code,zipcode.city,zipcode.city_alias_name,zipcode.country,zipcode.county,zipcode.county_fips,zipcode.state_fips,zipcode.time_zone,zipcode.day_light_saving,zipcode.msa,zipcode.pmsa,zipcode.csa,zipcode.cbsa,zipcode.cbsa_div,zipcode.cbsa_type,zipcode.cbsa_name,zipcode.msa_name,zipcode.pmsa_name,zipcode.region,zipcode.division,zipcode.mailing_name,zipcode.preferred_last_line_key,zipcode.classification_code,zipcode.multi_county,zipcode.csa_name,zipcode.cbsa_div_name,zipcode.city_state_key,zipcode.city_alias_code,zipcode.city_mixed_case,zipcode.city_alias_mixed_case,zipcode.state_ansi,zipcode.county_ansi,zipcode.facility_code,zipcode.city_delivery_indicator,zipcode.carrier_route_rate_sortation,zipcode.finance_number,zipcode.unique_zip_name
0,1,501,NaN,P,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,40.815400,-73.045600,25,NY,New York,P,NaN,631,Holtsville,Holtsville,US,Suffolk,103.0,36.0,5,Y,5602.0,5380.0,408.0,35620.0,35004.0,Metro,New York-Newark-Jersey City NY-NJ-PA,New York-Northern New Jersey-Long Island NY-NJ...,Nassau-Suffolk NY PMSA,Northeast,Middle Atlantic,Y,V13916,U,NaN,"New York-Newark, NY-NJ-CT-PA","Nassau County-Suffolk County, NY",V13916,G,Holtsville,Holtsville,36.0,103.0,P,N,C,353910.0,NaN
1,2,501,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,40.815400,-73.045600,25,NY,New York,N,NaN,631,Holtsville,Internal Revenue Service,US,Suffolk,103.0,36.0,5,Y,5602.0,5380.0,408.0,35620.0,35004.0,Metro,New York-Newark-Jersey City NY-NJ-PA,New York-Northern New Jersey-Long Island NY-NJ...,Nassau-Suffolk NY PMSA,Northeast,Middle Atlantic,N,V13916,U,NaN,"New York-Newark, NY-NJ-CT-PA","Nassau County-Suffolk County, NY",V14021,G,Holtsville,Internal Revenue Service,36.0,103.0,N,N,C,353910.0,Y
2,3,544,NaN,P,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,40.815400,-73.045600,25,NY,New York,P,NaN,631,Holtsville,Holtsville,US,Suffolk,103.0,36.0,5,Y,5602.0,5380.0,408.0,35620.0,35004.0,Metro,New York-Newark-Jersey City NY-NJ-PA,New York-Northern New Jersey-Long Island NY-NJ...,Nassau-Suffolk NY PMSA,Northeast,Middle Atlantic,Y,V13916,U,NaN,"New York-Newark, NY-NJ-CT-PA","Nassau County-Suffolk County, NY",V13916,G,Holtsville,Holtsville,36.0,103.0,P,N,C,353910.0,NaN
3,4,544,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,40.815400,-73.045600,25,NY,New York,N,NaN,631,Holtsville,Internal Revenue Service,US,Suffolk,103.0,36.0,5,Y,5602.0,5380.0,408.0,35620.0,35004.0,Metro,New York-Newark-Jersey City NY-NJ-PA,New York-Northern New Jersey-Long Island NY-NJ...,Nassau-Suffolk NY PMSA,Northeast,Middle Atlantic,N,V13916,U,NaN,"New York-Newark, NY-NJ-CT-PA","Nassau County-Suffolk County, NY",V14021,G,Holtsville,Internal Revenue Service,36.0,103.0,N,N,C,353910.0,Y
4,5,601,NaN,P,18570,6525,17479,663,18486,7,10,113,558,9078,9492,2.84,104600,12041,18.196747,-66.736735,0,PR,Puerto Rico,P,NaN,787/939,Adjuntas,Adjuntas,US,Adjuntas,1.0,72.0,4,N,NaN,NaN,434.0,10260.0,NaN,Micro,Adjuntas PR,NaN,NaN,NaN,NaN,Y,V17135,NaN,NaN,"Ponce-Coamo-Santa Isabel, PR",NaN,V17135,NaN,Adjuntas,Adjuntas,72.0,1.0,P,Y,C,420180.0,NaN