In [1]:
type(hash('100'))

int

In [2]:
hash('100')

163512108406620378

In [3]:
testcode=[  1641,    393,   8629,   8491,  26086,   2296,    663,   1588,
        25764,   8533,   4981,   6187,   3268,   4237,    343,   3078,
         6643, 106002,    338,   3554]

In [4]:
import os
import pandas as pd
import math
import findspark

findspark.init('/usr/hdp/2.6.0.3-8/spark')

In [5]:
from pyspark.mllib.recommendation import ALS, MatrixFactorizationModel, Rating
from pyspark import rdd, SparkContext, SparkFiles
sc=SparkContext()

In [6]:
def single_test0(userID, codes):
    results=[]
#     userID = np.random.randint(1000,2000)
    for i in codes:
        results.append((u"{},{},1".format(userID,i)))
    print len(results)
    return results

In [7]:
new = sc.parallelize(single_test0(2000, testcode))
type(new)

20

pyspark.rdd.RDD

In [8]:
new.take(3)

[u'2000,1641,1', u'2000,393,1', u'2000,8629,1']

In [9]:
%%time
fl = sc.textFile('file:///home/soyoung/HackerInsurTech/midsample.csv')
print type(fl)
header = fl.first() #extract header
fl = fl.filter(lambda x: x!=header)

<class 'pyspark.rdd.RDD'>
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 205 ms

In [10]:
fl.take(3)

[u'1,110,0', u'1,147,1', u'1,858,1']

In [11]:
data = sc.union([fl,new])
data.take(3)

[u'1,110,0', u'1,147,1', u'1,858,1']

___

In [12]:
# Rating??

In [13]:
ratings = data.map(lambda l: l.split(',')).map(lambda l: Rating(int(l[0]), int(str(l[1])), float(l[2])))

In [14]:
rank = 10
numIterations = 10

In [15]:
%%time
model = ALS.train(ratings, rank, numIterations)

CPU times: user 16 ms, sys: 4 ms, total: 20 ms
Wall time: 15.2 s

In [16]:
ratings.take(1)

[Rating(user=1, product=110, rating=0.0)]

In [17]:
ratings.take(1)[0][0:2]

(1, 110)

___

In [18]:
def single_test(userID, codes):
    results=[]
#     userID = np.random.randint(1000,2000)
    for i in codes:
        results.append((userID, i))
    print len(results)
    return results

In [19]:
ratings.filter(lambda x: x[0] == 2000).map(lambda p: (p[0], p[1]))

PythonRDD[222] at RDD at PythonRDD.scala:43

In [20]:
%%time
results = model.predictAll(ratings.filter(lambda x: x[0] == 2000).map(lambda p: (p[0], p[1])))

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 4.43 s

In [21]:
from pyspark.sql.types import StructType
from pyspark.sql.types import StructField
from pyspark.sql.types import StringType, IntegerType, FloatType

from pyspark.sql import SQLContext
sqlContext = SQLContext(sc)

schema = StructType([StructField('userID', IntegerType(), True), 
                     StructField('codeID', IntegerType(), True), 
                     StructField('valid_prob', FloatType(), True)])

In [24]:
%%time
results = model.predictAll(sc.parallelize(single_test(2000, testcode)))

20
CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 140 ms

In [25]:
df = sqlContext.createDataFrame(results, schema)
df

DataFrame[userID: int, codeID: int, valid_prob: float]

In [26]:
df.toPandas()

    userID  codeID  valid_prob
0     2000    2296    0.639720
1     2000    3268    0.247785
2     2000   25764    0.962311
3     2000    1588    0.317930
4     2000    1641    0.779639
5     2000    8629    0.996244
6     2000    4237    0.898537
7     2000    4981    1.001502
8     2000     393    0.404499
9     2000    8533    0.712773
10    2000    3078    0.877030
11    2000  106002    0.680610
12    2000     338    0.495683
13    2000    3554    1.199219
14    2000   26086    0.924305
15    2000     663    0.363423
16    2000    6643    0.693366
17    2000    6187    0.561305
18    2000     343    0.416329
19    2000    8491    0.965511

___

In [21]:
%%time
codes = pd.read_csv('./sample.csv', usecols=['codeID'])['codeID'].unique()

CPU times: user 16 ms, sys: 12 ms, total: 28 ms
Wall time: 36.1 ms

In [22]:
sc.parallelize([(1, 2), (3, 4)]).collect()

[(1, 2), (3, 4)]

In [23]:
%%time
results = model.predictAll(sc.parallelize(single_test(2000, codes)))

9066
CPU times: user 80 ms, sys: 0 ns, total: 80 ms
Wall time: 182 ms

In [24]:
df = sqlContext.createDataFrame(results, schema)
dfp =df.toPandas()
dfp

      userID  codeID  valid_prob
0       2000    1084    0.857796
1       2000    6400    0.915096
2       2000   81132   -0.258463
3       2000    6308    0.902392
4       2000   44828   -0.280645
5       2000    7020    1.082411
6       2000    5384    1.039434
7       2000    7136    0.340912
8       2000     140    0.480365
9       2000     204    0.259831
10      2000     956    0.287236
11      2000    4992    0.798336
12      2000   62912   -0.638719
13      2000    4224    0.957423
14      2000   73168   -1.018394
15      2000     160    0.154647
16      2000   72176    0.169465
17      2000    7456    0.427022
18      2000    1596   -0.197832
19      2000    3932    0.838738
20      2000    2904    0.064529
21      2000    6840    0.101855
22      2000    4628    1.039195
23      2000    1500    0.694591
24      2000   55276    0.432878
25      2000     548    0.365079
26      2000   46772   -1.021271
27      2000    1732    0.611547
28      2000   78544    0.746295
29      2000   94780   -0.557438
...      ...     ...         ...
8712    2000    6731    0.269998
8713    2000   78499    0.345339
8714    2000    8999    0.543735
8715    2000   71823    0.962777
8716    2000    5315   -0.040456
8717    2000    6195    0.891068
8718    2000    6091    0.000000
8719    2000    2983    0.921133
8720    2000    5799    1.154091
8721    2000     183    0.923599
8722    2000    3699    0.433168
8723    2000   37211    0.772243
8724    2000    2395    0.288860
8725    2000    3431    0.760098
8726    2000   91199    1.184335
8727    2000    3299   -0.176165
8728    2000    7171    1.661003
8729    2000    1103    0.994193
8730    2000   59387    0.542575
8731    2000    4487    0.738706
8732    2000    3503    0.841356
8733    2000    2003   -0.067979
8734    2000   32139    1.253565
8735    2000   93831   -0.613048
8736    2000  120799   -0.307632
8737    2000   95199    0.426948
8738    2000    3203    0.994690
8739    2000    5203    0.193379
8740    2000    7147    0.822179
8741    2000   96691   -0.059531

[8742 rows x 3 columns]

In [25]:
dfp[dfp['valid_prob']<0]

      userID  codeID  valid_prob
2       2000   81132   -0.258463
4       2000   44828   -0.280645
12      2000   62912   -0.638719
14      2000   73168   -1.018394
18      2000    1596   -0.197832
26      2000   46772   -1.021271
29      2000   94780   -0.557438
31      2000   91500   -0.262761
47      2000    8656   -0.024020
54      2000   50064   -0.187422
68      2000   95720   -0.341888
83      2000  104076   -0.103060
93      2000    5028   -0.489429
94      2000    5016   -0.131514
102     2000   93512   -0.743457
112     2000    6096   -0.582524
127     2000    4568   -0.660378
131     2000  114044   -0.530364
134     2000    3624   -0.060827
135     2000    7792   -0.316608
140     2000   71876   -0.350448
158     2000   80860   -0.506797
163     2000    4528   -0.353776
180     2000   33836   -0.111356
182     2000    8964   -0.826755
189     2000    3664   -0.107526
191     2000   26684   -0.802469
195     2000    5544   -0.244256
197     2000   81784   -0.278891
202     2000   68444   -0.151507
...      ...     ...         ...
8536    2000     439   -0.147409
8549    2000  100083   -0.868674
8551    2000    1855   -0.033815
8552    2000    8667   -0.385712
8587    2000   48319   -0.654735
8594    2000   98083   -0.578453
8599    2000    3895   -0.189683
8606    2000   80363   -0.151706
8607    2000  112623   -0.180189
8614    2000      19   -0.304314
8622    2000  109895   -0.339708
8626    2000    6219   -0.385746
8631    2000    5447   -0.247325
8634    2000    1631   -0.096853
8656    2000   91323   -0.404361
8665    2000    5651   -0.814105
8667    2000   95307   -1.268139
8668    2000    7199   -0.196801
8671    2000   51091   -0.003956
8679    2000    4035   -0.075495
8680    2000   66659   -1.025121
8689    2000    6115   -0.290315
8698    2000   86911   -0.064505
8707    2000      55   -0.096462
8716    2000    5315   -0.040456
8727    2000    3299   -0.176165
8733    2000    2003   -0.067979
8735    2000   93831   -0.613048
8736    2000  120799   -0.307632
8741    2000   96691   -0.059531

[1438 rows x 3 columns]

In [26]:
dfp[dfp['valid_prob']<0.5]

      userID  codeID  valid_prob
2       2000   81132   -0.258463
4       2000   44828   -0.280645
7       2000    7136    0.340912
8       2000     140    0.480365
9       2000     204    0.259831
10      2000     956    0.287236
12      2000   62912   -0.638719
14      2000   73168   -1.018394
15      2000     160    0.154647
16      2000   72176    0.169465
17      2000    7456    0.427022
18      2000    1596   -0.197832
20      2000    2904    0.064529
21      2000    6840    0.101855
24      2000   55276    0.432878
25      2000     548    0.365079
26      2000   46772   -1.021271
29      2000   94780   -0.557438
30      2000   54648    0.345287
31      2000   91500   -0.262761
32      2000  128592    0.000000
33      2000     528    0.334254
35      2000     196    0.348533
39      2000    4228    0.178809
40      2000   84944    0.471768
45      2000    4424    0.494501
47      2000    8656   -0.024020
52      2000   54328    0.309014
54      2000   50064   -0.187422
55      2000    1468    0.198901
...      ...     ...         ...
8680    2000   66659   -1.025121
8682    2000    4963    0.370514
8686    2000    8187    0.000000
8689    2000    6115   -0.290315
8690    2000    2719    0.172978
8693    2000    8983    0.454340
8696    2000    2815    0.283052
8698    2000   86911   -0.064505
8699    2000   48043    0.279669
8701    2000    4835    0.123764
8702    2000     619    0.414954
8703    2000  116887    0.129449
8704    2000    2087    0.400169
8705    2000    3763    0.261728
8706    2000   64575    0.462340
8707    2000      55   -0.096462
8709    2000    6611    0.373596
8712    2000    6731    0.269998
8713    2000   78499    0.345339
8716    2000    5315   -0.040456
8718    2000    6091    0.000000
8722    2000    3699    0.433168
8724    2000    2395    0.288860
8727    2000    3299   -0.176165
8733    2000    2003   -0.067979
8735    2000   93831   -0.613048
8736    2000  120799   -0.307632
8737    2000   95199    0.426948
8739    2000    5203    0.193379
8741    2000   96691   -0.059531

[4758 rows x 3 columns]

In [27]:
dfp[dfp['valid_prob']>0.95]

      userID  codeID  valid_prob
5       2000    7020    1.082411
6       2000    5384    1.039434
13      2000    4224    0.957423
22      2000    4628    1.039195
41      2000    4304    1.290364
51      2000    7560    1.352558
60      2000    3700    1.020728
65      2000    1044    0.981795
71      2000    2976    1.047243
77      2000    3304    1.567619
82      2000   25916    1.335509
98      2000    8712    1.363694
109     2000    6284    1.270759
111     2000   43396    1.112657
121     2000    7012    1.273951
126     2000   98604    1.503927
132     2000    6116    1.044739
136     2000    5168    1.546471
144     2000   97744    1.161283
153     2000    2948    1.068098
160     2000    1092    1.076065
183     2000    6244    1.067825
187     2000   31364    1.027274
221     2000    3832    1.164990
232     2000     504    1.535665
236     2000    6612    1.040600
237     2000   27724    1.157477
252     2000      36    1.027501
256     2000     924    1.017045
258     2000    4012    1.505323
...      ...     ...         ...
8521    2000   26663    0.951000
8524    2000    5383    1.575912
8526    2000  103539    1.019037
8543    2000    8263    1.006958
8545    2000     527    1.034136
8568    2000    2847    1.858312
8571    2000  142507    1.009242
8572    2000    1927    1.441047
8584    2000    2803    0.956689
8585    2000     563    1.156281
8588    2000   49647    1.184627
8591    2000    7219    1.305483
8595    2000   25827    1.001050
8608    2000  151639    1.102047
8611    2000    1835    1.170171
8617    2000    2647    1.509524
8620    2000   68099    1.108060
8629    2000   55207    1.214060
8630    2000    2443    1.287683
8663    2000    8575    1.478764
8666    2000  134859    1.233080
8673    2000   96467    0.993551
8674    2000    2775    1.074996
8715    2000   71823    0.962777
8720    2000    5799    1.154091
8726    2000   91199    1.184335
8728    2000    7171    1.661003
8729    2000    1103    0.994193
8734    2000   32139    1.253565
8738    2000    3203    0.994690

[1074 rows x 3 columns]